'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { 
  Box, Typography, Card, CardContent, Button, TextField, 
  Chip, CircularProgress, Alert, IconButton, InputAdornment,
  Grid, Divider, Dialog, DialogTitle, DialogContent, Tabs, Tab
} from '@mui/material';
import {
  Search, FilterList, ShoppingCart, Visibility, Favorite,
  Refresh, Close, Verified, Collections, Hexagon
} from '@mui/icons-material';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080';

interface NFT {
  id: string;
  token_id: string;
  contract_address: string;
  name: string;
  symbol: string;
  description: string;
  image_url: string;
  animation_url?: string;
  attributes: { trait_type: string; value: string; rarity?: string }[];
  owner: string;
  price: number;
  price_token: string;
  chain_id: number;
}

interface NFTCollection {
  id: string;
  name: string;
  symbol: string;
  contract_address: string;
  chain_id: number;
  total_supply: number;
  floor_price: number;
  volume_24h: number;
  image_url: string;
}

const CHAIN_NAMES: Record<number, string> = {
  1: 'Ethereum',
  56: 'BNB Chain',
  137: 'Polygon',
  42161: 'Arbitrum',
  43114: 'Avalanche',
};

export default function NFTMarketplace() {
  const [activeTab, setActiveTab] = useState(0);
  const [nfts, setNfts] = useState<NFT[]>([]);
  const [collections, setCollections] = useState<NFTCollection[]>([]);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [selectedNFT, setSelectedNFT] = useState<NFT | null>(null);
  const [walletAddress, setWalletAddress] = useState<string>('');
  const [buyDialogOpen, setBuyDialogOpen] = useState(false);

  useEffect(() => {
    const savedWallet = localStorage.getItem('tigerwallet_address');
    if (savedWallet) {
      setWalletAddress(savedWallet);
    }
  }, []);

  const fetchNFTs = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_BASE}/api/v1/nft/items?chain_id=1`);
      if (response.ok) {
        const data = await response.json();
        if (data.items && data.items.length > 0) {
          setNfts(data.items);
        } else {
          setDefaultNFTs();
        }
      } else {
        setDefaultNFTs();
      }
    } catch (err) {
      setDefaultNFTs();
    } finally {
      setIsLoading(false);
    }
  }, []);

  const setDefaultNFTs = () => {
    setNfts([
      {
        id: 'nft_1',
        token_id: '1234',
        contract_address: '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D',
        name: 'Bored Ape Yacht Club #1234',
        symbol: 'BAYC',
        description: 'The Bored Ape Yacht Club is a collection of 10,000 unique Bored Ape NFTs.',
        image_url: '',
        attributes: [
          { trait_type: 'Background', value: 'Blue', rarity: '20%' },
          { trait_type: 'Fur', value: 'Dark Brown', rarity: '15%' },
          { trait_type: 'Eyes', value: 'Bored', rarity: '30%' },
        ],
        owner: '0x742d35Cc6634C053292505a5eC874A66E8535F5F',
        price: 35.0,
        price_token: 'ETH',
        chain_id: 1,
      },
      {
        id: 'nft_2',
        token_id: '5678',
        contract_address: '0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB',
        name: 'CryptoPunk #5678',
        symbol: 'PUNK',
        description: 'CryptoPunks are 24x24 pixel art images generated by an algorithm.',
        image_url: '',
        attributes: [
          { trait_type: 'Type', value: 'Alien', rarity: '1%' },
          { trait_type: 'Accessory', value: 'Pipe', rarity: '5%' },
        ],
        owner: '0x123d35Cc6634C053292505a5eC874A66E8535F5F',
        price: 50.0,
        price_token: 'ETH',
        chain_id: 1,
      },
      {
        id: 'nft_3',
        token_id: '9012',
        contract_address: '0xED5AF388653567Af2F388E6224dC7C4b3241C544',
        name: 'Azuki #9012',
        symbol: 'AZUKI',
        description: 'Azuki starts with a collection of 10,000 avatars that give you membership access to The Garden.',
        image_url: '',
        attributes: [
          { trait_type: 'Type', value: 'Human', rarity: '80%' },
          { trait_type: 'Hair', value: 'Pink Hair', rarity: '10%' },
        ],
        owner: '0x456d35Cc6634C053292505a5eC874A66E8535F5F',
        price: 15.0,
        price_token: 'ETH',
        chain_id: 1,
      },
    ]);
  };

  const fetchCollections = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE}/api/v1/nft/collections?chain_id=1`);
      if (response.ok) {
        const data = await response.json();
        if (data.collections) {
          setCollections(data.collections);
        }
      }
    } catch (err) {
      // Collections not available
    }
  }, []);

  useEffect(() => {
    fetchNFTs();
    fetchCollections();
  }, [fetchNFTs, fetchCollections]);

  const filteredNFTs = nfts.filter(nft => {
    const matchesSearch = nft.name.toLowerCase().includes(search.toLowerCase()) || 
                         nft.symbol.toLowerCase().includes(search.toLowerCase());
    if (filter === 'all') return matchesSearch;
    return matchesSearch && nft.chain_id === parseInt(filter);
  });

  const handleBuy = async (nft: NFT) => {
    if (!walletAddress) {
      setError('Please connect your wallet first');
      return;
    }

    setIsLoading(true);
    setError(null);
    setSuccess(null);

    try {
      const token = localStorage.getItem('tigerwallet_token');
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (token) headers['Authorization'] = `Bearer ${token}`;

      const response = await fetch(`${API_BASE}/api/v1/nft/buy`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          nft_id: nft.id,
          price: nft.price,
          price_token: nft.price_token,
        }),
      });

      const data = await response.json();
      if (data.success && data.tx_hash) {
        setSuccess(`Successfully purchased ${nft.name}! TX: ${data.tx_hash}`);
        setBuyDialogOpen(false);
        setSelectedNFT(null);
      } else {
        setError(data.error || 'Purchase failed');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Purchase failed');
    } finally {
      setIsLoading(false);
    }
  };

  const getNFTIcon = (symbol: string) => {
    switch (symbol) {
      case 'BAYC': return '🦧';
      case 'PUNK': return '👽';
      case 'AZUKI': return '🥷';
      case 'DEGOD': return '👻';
      case 'MILADY': return '💄';
      default: return '🎨';
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-50 p-6">
      <header className="mb-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <span className="text-4xl">🖼️</span>
            <h1 className="text-2xl font-bold">NFT Marketplace</h1>
          </div>
          {walletAddress ? (
            <Chip 
              label={`${walletAddress.slice(0, 6)}...${walletAddress.slice(-4)}`}
              className="bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            />
          ) : (
            <Button 
              variant="contained" 
              onClick={() => setError('Please connect wallet first')}
              className="bg-orange-500 hover:bg-orange-600"
            >
              Connect Wallet
            </Button>
          )}
        </div>
      </header>

      <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} className="mb-6">
        <Tab label="Explore" />
        <Tab label="Collections" />
        <Tab label="My NFTs" />
      </Tabs>

      <div className="flex flex-wrap gap-4 mb-6">
        <TextField
          placeholder="Search NFTs..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          size="small"
          className="flex-1 min-w-[200px]"
          InputProps={{
            startAdornment: <InputAdornment position="start"><Search /></InputAdornment>,
          }}
        />
        <Box className="flex gap-2">
          {['all', '1', '56', '137'].map(chain => (
            <Button 
              key={chain}
              variant={filter === chain ? 'contained' : 'outlined'}
              onClick={() => setFilter(chain)}
              size="small"
              className={filter === chain ? 'bg-orange-500' : ''}
            >
              {chain === 'all' ? 'All' : CHAIN_NAMES[parseInt(chain)] || chain}
            </Button>
          ))}
        </Box>
      </div>

      {error && <Alert severity="error" className="mb-4" onClose={() => setError(null)}>{error}</Alert>}
      {success && <Alert severity="success" className="mb-4" onClose={() => setSuccess(null)}>{success}</Alert>}

      {isLoading && (
        <Box className="flex justify-center py-12">
          <CircularProgress />
        </Box>
      )}

      {!isLoading && (
        <Grid container spacing={3}>
          {filteredNFTs.map(nft => (
            <Grid item xs={12} sm={6} md={4} lg={3} key={nft.id}>
              <Card 
                className="bg-white dark:bg-slate-800 hover:shadow-xl transition-shadow cursor-pointer"
                onClick={() => { setSelectedNFT(nft); setBuyDialogOpen(true); }}
              >
                <Box className="h-48 bg-gradient-to-br from-orange-400 to-pink-500 flex items-center justify-center text-6xl">
                  {getNFTIcon(nft.symbol)}
                </Box>
                <CardContent>
                  <Box className="flex items-center gap-1 mb-1">
                    <Typography variant="caption" className="text-slate-500 dark:text-slate-400">
                      {nft.symbol}
                    </Typography>
                    <Verified fontSize="small" className="text-blue-500" />
                  </Box>
                  <Typography variant="subtitle1" className="font-semibold mb-1">
                    {nft.name}
                  </Typography>
                  <Typography variant="body2" className="mb-2 text-slate-500 dark:text-slate-400" noWrap>
                    {nft.description?.substring(0, 50)}...
                  </Typography>
                  <Box className="flex justify-between items-center">
                    <Chip 
                      label={CHAIN_NAMES[nft.chain_id] || `Chain ${nft.chain_id}`} 
                      size="small"
                      className="bg-slate-200 dark:bg-slate-700"
                    />
                    <Typography variant="subtitle2" className="text-orange-500">
                      {nft.price} {nft.price_token}
                    </Typography>
                  </Box>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}

      {filteredNFTs.length === 0 && !isLoading && (
        <Box className="text-center py-12">
          <Collections className="text-6xl text-slate-400 mb-4" />
          <Typography variant="h6" className="text-slate-500 dark:text-slate-400">
            No NFTs found
          </Typography>
        </Box>
      )}

      <Dialog open={buyDialogOpen && !!selectedNFT} onClose={() => { setBuyDialogOpen(false); setSelectedNFT(null); }} maxWidth="md" fullWidth>
        {selectedNFT && (
          <>
            <DialogTitle className="flex justify-between items-center">
              <span>{selectedNFT.name}</span>
              <IconButton onClick={() => { setBuyDialogOpen(false); setSelectedNFT(null); }}><Close /></IconButton>
            </DialogTitle>
            <DialogContent>
              <Grid container spacing={3}>
                <Grid item xs={12} md={6}>
                  <Box className="h-64 bg-gradient-to-br from-orange-400 to-pink-500 flex items-center justify-center text-8xl rounded-lg">
                    {getNFTIcon(selectedNFT.symbol)}
                  </Box>
                </Grid>
                <Grid item xs={12} md={6}>
                  <Typography variant="h6" className="mb-2">{selectedNFT.name}</Typography>
                  <Typography variant="body2" className="mb-4 text-slate-500 dark:text-slate-400">
                    {selectedNFT.description}
                  </Typography>
                  
                  <Divider className="my-3" />
                  
                  <Typography variant="subtitle2" className="mb-2">Attributes</Typography>
                  <Box className="flex flex-wrap gap-2 mb-4">
                    {selectedNFT.attributes?.map((attr, idx) => (
                      <Chip 
                        key={idx} 
                        label={`${attr.trait_type}: ${attr.value}`} 
                        size="small"
                        variant="outlined"
                      />
                    ))}
                  </Box>
                  
                  <Divider className="my-3" />
                  
                  <Box className="flex justify-between items-center mb-4">
                    <Box>
                      <Typography variant="caption" className="text-slate-500">Owner</Typography>
                      <Typography variant="body2">{selectedNFT.owner.slice(0, 8)}...{selectedNFT.owner.slice(-6)}</Typography>
                    </Box>
                    <Box className="text-right">
                      <Typography variant="caption" className="text-slate-500">Price</Typography>
                      <Typography variant="h5" className="text-orange-500">{selectedNFT.price} {selectedNFT.price_token}</Typography>
                    </Box>
                  </Box>
                  
                  <Button 
                    fullWidth 
                    variant="contained" 
                    className="bg-orange-500 hover:bg-orange-600"
                    onClick={() => handleBuy(selectedNFT)}
                    disabled={isLoading || !walletAddress}
                    startIcon={isLoading ? <CircularProgress size={24} /> : <ShoppingCart />}
                  >
                    {!walletAddress ? 'Connect Wallet' : isLoading ? 'Processing...' : 'Buy Now'}
                  </Button>
                </Grid>
              </Grid>
            </DialogContent>
          </>
        )}
      </Dialog>
    </div>
  );
}
