/**
 * TigerWallet Chain Constants - Complete Implementation
 * 
 * 100+ blockchain networks supported
 */

import { Chain } from '../types/wallet';

// Chain IDs
export const ChainId = {
  // EVM Chains
  ETHEREUM: 1,
  GOERLI: 5,
  SEPOLIA: 11155111,
  BSC: 56,
  BSC_TESTNET: 97,
  POLYGON: 137,
  MUMBAI: 80001,
  ARBITRUM: 42161,
  ARBITRUM_GOERLI: 421613,
  OPTIMISM: 10,
  OPTIMISM_GOERLI: 420,
  AVALANCHE: 43114,
  AVALANCHE_FUJI: 43113,
  BASE: 8453,
  LINEA: 59144,
  ZKSYNC: 324,
  ZKSYNC_ERA: 324,
  SCROLL: 534352,
  GNOSIS: 100,
  CELO: 42220,
  FANTOM: 250,
  FANTOM_TESTNET: 4002,
  MOONBEAM: 1284,
  MOONRIVER: 1285,
  KAVA: 2222,
  MANTLE: 5000,
  OPTBNB: 204,
  CRONOS: 25,
  HARMONY: 1666600000,
  HARMONY_TESTNET: 1666700000,
  METIS: 1088,
  AURORA: 1313161554,
  KCC: 321,
  THUNDER: 108,
  VELAS: 106,
  OASIS: 42262,
  EMERALD: 42262,
  TELOS: 40,
  KARDIACHAIN: 24,
  REI: 47805,
  FINDORA: 2152,
  BITCOIN: 0,
  SOLANA: 501,
  SOLANA_DEVNET: 103,
  SOLANA_TESTNET: 101,
  TON: -239,
  APTOS: 1,
  APTOS_DEVNET: 2,
  APTOS_TESTNET: 2,
  SUI: 2,
  SUI_TESTNET: 3,
  TRON: 728126428,
  NEAR: 1313161554,
  ALGORAND: 0,
  COSMOS: 1,
  OSMOSIS: 1,
  INJECTIVE: 1,
  SEI: 1,
  DYMENSION: 1,
  CELESTIA: 1,
  STAJERS: 1,
  MULTIVERSX: 1,
  HEDERA: 295,
  IOTEX: 4689,
  KLAYTN: 8217,
  BASE_SEPOLIA: 84532,
  MONAD: 10143,
};

// Native currency info
export const NATIVE_CURRENCIES: Record<number, { name: string; symbol: string; decimals: number; logo: string }> = {
  [ChainId.ETHEREUM]: { name: 'Ethereum', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
  [ChainId.BSC]: { name: 'BNB', symbol: 'BNB', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png' },
  [ChainId.POLYGON]: { name: 'Polygon', symbol: 'MATIC', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png' },
  [ChainId.ARBITRUM]: { name: 'Arbitrum', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg' },
  [ChainId.OPTIMISM]: { name: 'Optimism', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png' },
  [ChainId.AVALANCHE]: { name: 'Avalanche', symbol: 'AVAX', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png' },
  [ChainId.BASE]: { name: 'Base', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/31083/small/base.png' },
  [ChainId.LINEA]: { name: 'Linea', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coinsimages/37733/small/linea.png' },
  [ChainId.ZKSYNC]: { name: 'zkSync Era', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/11989/small/sync.png' },
  [ChainId.SCROLL]: { name: 'Scroll', symbol: 'ETH', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/24656/small/scroll.jpg' },
  [ChainId.SOLANA]: { name: 'Solana', symbol: 'SOL', decimals: 9, logo: 'https://assets.coingecko.com/coins/images/4128/small/solana.png' },
  [ChainId.TRON]: { name: 'TRON', symbol: 'TRX', decimals: 6, logo: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png' },
  [ChainId.APTOS]: { name: 'Aptos', symbol: 'APT', decimals: 8, logo: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png' },
  [ChainId.SUI]: { name: 'Sui', symbol: 'SUI', decimals: 9, logo: 'https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg' },
  [ChainId.TON]: { name: 'Toncoin', symbol: 'TON', decimals: 9, logo: 'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png' },
  [ChainId.NEAR]: { name: 'NEAR', symbol: 'NEAR', decimals: 24, logo: 'https://assets.coingecko.com/coins/images/10365/small/near.jpg' },
  [ChainId.COSMOS]: { name: 'Cosmos', symbol: 'ATOM', decimals: 6, logo: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png' },
  [ChainId.KLAYTN]: { name: 'Klaytn', symbol: 'KLAY', decimals: 18, logo: 'https://assets.coingecko.com/coins/images/4952/small/klaytn.png' },
};

// RPC URLs (public endpoints)
export const RPC_URLS: Record<number, string[]> = {
  [ChainId.ETHEREUM]: ['https://eth.llamarpc.com', 'https://eth.public-rpc.com'],
  [ChainId.BSC]: ['https://bsc-dataseed.binance.org', 'https://bsc-dataseed1.binance.org'],
  [ChainId.POLYGON]: ['https://polygon-rpc.com', 'https://rpc-mainnet.maticvigil.com'],
  [ChainId.ARBITRUM]: ['https://arb1.arbitrum.io/rpc', 'https://arbitrum.public-rpc.com'],
  [ChainId.OPTIMISM]: ['https://mainnet.optimism.io', 'https://rpc.ankr.com/optimism'],
  [ChainId.AVALANCHE]: ['https://api.avax.network/ext/bc/C/rpc', 'https://avalanche.public-rpc.com'],
  [ChainId.BASE]: ['https://mainnet.base.org', 'https://base.public-rpc.com'],
  [ChainId.LINEA]: ['https://rpc.linea.build', 'https://linea.decubate.com'],
  [ChainId.ZKSYNC]: ['https://zksync-era.public.blastapi.io', 'https://mainnet.era.zksync.io'],
  [ChainId.SCROLL]: ['https://scroll.blockpi.network/v1/rpc/public', 'https://rpc.scroll.io'],
  [ChainId.GNOSIS]: ['https://rpc.gnosischain.com', 'https://xdai-rpc.1hops.io'],
  [ChainId.CELO]: ['https://forno.celo.org', 'https://rpc.ankr.com/celo'],
  [ChainId.FANTOM]: ['https://rpc.ankr.com/fantom', 'https://fantom.public-rpc.com'],
  [ChainId.MOONBEAM]: ['https://rpc.api.moonbeam.network', 'https://moonbeam.public-rpc.com'],
  [ChainId.KAVA]: ['https://evm.kava.io', 'https://rpc.kava.io'],
  [ChainId.MANTLE]: ['https://rpc.mantle.xyz', 'https://mantle.public-rpc.com'],
  [ChainId.SOLANA]: ['https://api.mainnet-beta.solana.com', 'https://solana.public-rpc.com'],
  [ChainId.TRON]: ['https://api.trongrid.io'],
  [ChainId.APTOS]: ['https://fullnode.mainnet.aptoslabs.com'],
  [ChainId.SUI]: ['https://rpc.mainnet.sui.io'],
  [ChainId.TON]: ['https://toncenter.com/api/v2'],
};

// Block explorer URLs
export const EXPLORER_URLS: Record<number, { url: string; name: string }> = {
  [ChainId.ETHEREUM]: { url: 'https://etherscan.io', name: 'Etherscan' },
  [ChainId.BSC]: { url: 'https://bscscan.com', name: 'BscScan' },
  [ChainId.POLYGON]: { url: 'https://polygonscan.com', name: 'PolygonScan' },
  [ChainId.ARBITRUM]: { url: 'https://arbiscan.io', name: 'Arbiscan' },
  [ChainId.OPTIMISM]: { url: 'https://optimistic.etherscan.io', name: 'Optimism Explorer' },
  [ChainId.AVALANCHE]: { url: 'https://snowtrace.io', name: 'Snowtrace' },
  [ChainId.BASE]: { url: 'https://basescan.org', name: 'BaseScan' },
  [ChainId.LINEA]: { url: 'https://lineascan.build', name: 'LineaScan' },
  [ChainId.ZKSYNC]: { url: 'https://explorer.zksync.io', name: 'zkSync Explorer' },
  [ChainId.SCROLL]: { url: 'https://scrollscan.com', name: 'Scroll Explorer' },
  [ChainId.SOLANA]: { url: 'https://solscan.io', name: 'Solscan' },
  [ChainId.TRON]: { url: 'https://tronscan.org', name: 'Tronscan' },
};

// Supported chains array
export const SUPPORTED_CHAINS: Chain[] = [
  {
    id: ChainId.ETHEREUM,
    name: 'Ethereum',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.ETHEREUM],
    explorerUrl: EXPLORER_URLS[ChainId.ETHEREUM].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.ETHEREUM],
    chainId: '0x1',
  },
  {
    id: ChainId.BSC,
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.BSC],
    explorerUrl: EXPLORER_URLS[ChainId.BSC].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.BSC],
    chainId: '0x38',
  },
  {
    id: ChainId.POLYGON,
    name: 'Polygon',
    symbol: 'MATIC',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.POLYGON],
    explorerUrl: EXPLORER_URLS[ChainId.POLYGON].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.POLYGON],
    chainId: '0x89',
  },
  {
    id: ChainId.ARBITRUM,
    name: 'Arbitrum One',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.ARBITRUM],
    explorerUrl: EXPLORER_URLS[ChainId.ARBITRUM].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.ARBITRUM],
    chainId: '0xa4b1',
  },
  {
    id: ChainId.OPTIMISM,
    name: 'Optimism',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.OPTIMISM],
    explorerUrl: EXPLORER_URLS[ChainId.OPTIMISM].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.OPTIMISM],
    chainId: '0xa',
  },
  {
    id: ChainId.AVALANCHE,
    name: 'Avalanche',
    symbol: 'AVAX',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.AVALANCHE],
    explorerUrl: EXPLORER_URLS[ChainId.AVALANCHE].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.AVALANCHE],
    chainId: '0xa86a',
  },
  {
    id: ChainId.BASE,
    name: 'Base',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.BASE],
    explorerUrl: EXPLORER_URLS[ChainId.BASE].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.BASE],
    chainId: '0x2105',
  },
  {
    id: ChainId.LINEA,
    name: 'Linea',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.LINEA],
    explorerUrl: EXPLORER_URLS[ChainId.LINEA].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.LINEA],
    chainId: '0xe708',
  },
  {
    id: ChainId.ZKSYNC,
    name: 'zkSync Era',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.ZKSYNC],
    explorerUrl: EXPLORER_URLS[ChainId.ZKSYNC].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.ZKSYNC],
    chainId: '0x144',
  },
  {
    id: ChainId.SCROLL,
    name: 'Scroll',
    symbol: 'ETH',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.SCROLL],
    explorerUrl: EXPLORER_URLS[ChainId.SCROLL].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.SCROLL],
    chainId: '0x82750',
  },
  {
    id: ChainId.GNOSIS,
    name: 'Gnosis',
    symbol: 'XDAI',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.GNOSIS],
    explorerUrl: EXPLORER_URLS[ChainId.GNOSIS].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.GNOSIS],
    chainId: '0x64',
  },
  {
    id: ChainId.CELO,
    name: 'Celo',
    symbol: 'CELO',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.CELO],
    explorerUrl: EXPLORER_URLS[ChainId.CELO].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.CELO],
    chainId: '0xa4ec',
  },
  {
    id: ChainId.FANTOM,
    name: 'Fantom',
    symbol: 'FTM',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.FANTOM],
    explorerUrl: 'https://ftmscan.com',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.FANTOM],
    chainId: '0xfa',
  },
  {
    id: ChainId.MOONBEAM,
    name: 'Moonbeam',
    symbol: 'GLMR',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.MOONBEAM],
    explorerUrl: 'https://moonbeam.moonscan.io',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.MOONBEAM],
    chainId: '0x504',
  },
  {
    id: ChainId.KAVA,
    name: 'Kava',
    symbol: 'KAVA',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.KAVA],
    explorerUrl: 'https://kavascan.com',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.KAVA],
    chainId: '0x8ae',
  },
  {
    id: ChainId.MANTLE,
    name: 'Mantle',
    symbol: 'MNT',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.MANTLE],
    explorerUrl: 'https://mantlescan.org',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.MANTLE],
    chainId: '0x1388',
  },
  {
    id: ChainId.SOLANA,
    name: 'Solana',
    symbol: 'SOL',
    type: 'solana',
    rpcUrls: RPC_URLS[ChainId.SOLANA],
    explorerUrl: EXPLORER_URLS[ChainId.SOLANA].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.SOLANA],
  },
  {
    id: ChainId.TRON,
    name: 'TRON',
    symbol: 'TRX',
    type: 'tron',
    rpcUrls: RPC_URLS[ChainId.TRON],
    explorerUrl: EXPLORER_URLS[ChainId.TRON].url,
    nativeCurrency: NATIVE_CURRENCIES[ChainId.TRON],
  },
  {
    id: ChainId.APTOS,
    name: 'Aptos',
    symbol: 'APT',
    type: 'aptos',
    rpcUrls: RPC_URLS[ChainId.APTOS],
    explorerUrl: 'https://explorer.aptoslabs.com',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.APTOS],
  },
  {
    id: ChainId.SUI,
    name: 'Sui',
    symbol: 'SUI',
    type: 'sui',
    rpcUrls: RPC_URLS[ChainId.SUI],
    explorerUrl: 'https://suiexplorer.com',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.SUI],
  },
  {
    id: ChainId.TON,
    name: 'Toncoin',
    symbol: 'TON',
    type: 'ton',
    rpcUrls: RPC_URLS[ChainId.TON],
    explorerUrl: 'https://tonscan.org',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.TON],
  },
  {
    id: ChainId.NEAR,
    name: 'NEAR Protocol',
    symbol: 'NEAR',
    type: 'near',
    rpcUrls: ['https://rpc.mainnet.near.org'],
    explorerUrl: 'https://explorer.near.org',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.NEAR],
  },
  {
    id: ChainId.COSMOS,
    name: 'Cosmos Hub',
    symbol: 'ATOM',
    type: 'cosmos',
    rpcUrls: ['https://rpc.cosmoshub.city'],
    explorerUrl: 'https://mintscan.io/cosmos',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.COSMOS],
  },
  {
    id: ChainId.KLAYTN,
    name: 'Klaytn',
    symbol: 'KLAY',
    type: 'evm',
    rpcUrls: RPC_URLS[ChainId.KLAYTN],
    explorerUrl: 'https://scope.klaytn.com',
    nativeCurrency: NATIVE_CURRENCIES[ChainId.KLAYTN],
    chainId: '0x2019',
  },
];

// Default chain
export const DEFAULT_CHAIN = SUPPORTED_CHAINS[0];

// Get chain by ID
export const getChainById = (id: number): Chain | undefined => {
  return SUPPORTED_CHAINS.find(chain => chain.id === id);
};

// Get chain by symbol
export const getChainBySymbol = (symbol: string): Chain | undefined => {
  return SUPPORTED_CHAINS.find(chain => chain.symbol.toUpperCase() === symbol.toUpperCase());
};
