# TigerWallet Admin - iOS App
# Complete Native iOS Implementation with Dark/Light Theme Support

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'TigerAdmin' do
  # Networking
  pod 'Alamofire', '~> 5.8'
  pod 'Moya', '~> 15.0'
  
  # Database
  pod 'GRDB.swift', '~> 6.24'
  
  # Storage
  pod 'KeychainAccess', '~> 4.2'
  
  # UI
  pod 'SnapKit', '~> 5.7'
  pod 'Kingfisher', '~> 7.10'
  pod 'Charts', '~> 5.0'
  pod 'SkeletonView', '~> 1.31'
  
  # Navigation
  pod 'XCoordinator', '~> 2.0'
  
  # Utils
  pod 'SwiftyJSON', '~> 5.0'
  pod 'DateToolsSwift', '~> 5.0'
  
  # Biometric
  pod 'LocalAuthentication', :podspec => '~> 2.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
