//! ZK Proof Module.
//!
//! `ZKProof` carries the serialized Fiat-Shamir Schnorr proof generated by
//! `ZKProver`. The standalone `verify()` performs the same real Ristretto255
//! verification equation (s*G == R + e*Y) used by the prover, so a proof can be
//! checked without holding a reference to the prover that generated it.

use curve25519_dalek::constants;
use curve25519_dalek::ristretto::{CompressedRistretto, RistrettoPoint};
use curve25519_dalek::scalar::Scalar;
use curve25519_dalek::traits::IsIdentity;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha512};

const SCALAR_BYTES: usize = 32;
const POINT_BYTES: usize = 32;
const PROOF_BYTES: usize = POINT_BYTES + SCALAR_BYTES + POINT_BYTES;

/// ZK Proof
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ZKProof {
    pub proof_id: String,
    pub circuit_id: String,
    pub public_inputs: Vec<Vec<u8>>,
    pub private_inputs: Vec<Vec<u8>>,
    pub proof_data: Vec<u8>,
    pub created_at: i64,
    pub proof_type: ProofType,
    pub curve: CurveType,
}

impl ZKProof {
    pub fn new(circuit_id: String, proof_type: ProofType) -> Self {
        Self {
            proof_id: uuid::Uuid::new_v4().to_string(),
            circuit_id,
            public_inputs: Vec::new(),
            private_inputs: Vec::new(),
            proof_data: Vec::new(),
            created_at: chrono::Utc::now().timestamp(),
            proof_type,
            curve: CurveType::BN254,
        }
    }

    /// Verify this proof in isolation using the real Schnorr verification
    /// equation over Ristretto255. Returns `false` for a well-formed but
    /// invalid proof; never returns `true` for an empty/tampered proof.
    pub fn verify(&self) -> bool {
        if self.proof_data.len() != PROOF_BYTES {
            return false;
        }
        let data = self.proof_data.as_slice();
        let r_bytes = &data[..POINT_BYTES];
        let s_bytes = &data[POINT_BYTES..POINT_BYTES + SCALAR_BYTES];
        let y_bytes = &data[POINT_BYTES + SCALAR_BYTES..];

        let r = match CompressedRistretto::from_slice(r_bytes) {
            Ok(c) => match c.decompress() {
                Some(p) => p,
                None => return false,
            },
            Err(_) => return false,
        };
        let s = {
            let ct = Scalar::from_canonical_bytes(s_bytes.try_into().unwrap());
            if bool::from(ct.is_none()) {
                return false;
            }
            ct.unwrap()
        };
        let y = match CompressedRistretto::from_slice(y_bytes) {
            Ok(c) => match c.decompress() {
                Some(p) => p,
                None => return false,
            },
            Err(_) => return false,
        };
        if y.is_identity() {
            return false;
        }

        let e = challenge(&self.circuit_id, &self.public_inputs, &y, &r);
        let g = constants::RISTRETTO_BASEPOINT_POINT;
        g * s == r + e * y
    }
}

fn hash_to_scalar(domain: &[u8], parts: &[&[u8]]) -> Scalar {
    let mut h = Sha512::new();
    h.update(b"TigerSwap::ZK::Schnorr::Ristretto255::v1");
    h.update(domain);
    for p in parts {
        h.update((p.len() as u64).to_le_bytes());
        h.update(p);
    }
    Scalar::from_bytes_mod_order_wide(&h.finalize().into())
}

fn challenge(circuit_id: &str, public: &[Vec<u8>], y: &RistrettoPoint, r: &RistrettoPoint) -> Scalar {
    let mut pub_concat: Vec<u8> = Vec::new();
    for p in public {
        pub_concat.extend_from_slice(p);
    }
    hash_to_scalar(
        b"challenge",
        &[
            circuit_id.as_bytes(),
            &pub_concat,
            y.compress().as_bytes(),
            r.compress().as_bytes(),
        ],
    )
}

/// Proof type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofType {
    SNARK,
    STARK,
    PLONK,
    Halo2,
    Groth16,
}

/// Curve type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CurveType {
    BN254,
    BLS12_381,
    ED25519,
    SECP256K1,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_real_proof_roundtrip() {
        // Use the prover to mint a real proof, then verify it standalone.
        let prover = crate::ZKProver::new();
        prover
            .register_circuit(crate::ZKCircuit::new(
                "standalone".to_string(),
                "Standalone".to_string(),
                1,
            ))
            .await;
        prover.setup("standalone").await.unwrap();

        let inputs = crate::ZKProofInputs::new()
            .with_public(vec![vec![1, 2, 3]])
            .with_private(vec![vec![4, 5, 6]]);
        let proof = prover.prove("standalone", inputs).await.unwrap();

        assert!(proof.verify());
    }

    #[test]
    fn test_empty_proof_rejected() {
        let proof = ZKProof::new("x".to_string(), ProofType::SNARK);
        assert!(!proof.verify());
    }
}
