package main

// Code generated from the canonical ethereum-lists/chains registry
// (chainid.network/chains.json) for EVM + curated public mainnet docs for non-EVM.
// DO NOT EDIT by hand. These are the default chains seeded into the
// user_chains_evm / user_chains_nonevm tables on first boot. The master
// wallet owner can add/remove/update any chain at runtime via the REST API.

// defaultChain is the seed record for a default blockchain (EVM or non-EVM).
type defaultChain struct {
	ChainID        int64
	Name           string
	Symbol         string
	RPCURL         string
	ExplorerURL    string
	Decimals       int
	DerivationPath string
	ChainType      string // non-EVM only (EVM defaults to "evm")
	AddressPrefix  string // non-EVM bech32 prefix (cosmos/osmo, etc.)
}

// defaultEVMChains returns the 120 canonical EVM mainnet chains.
var defaultEVMChains = []defaultChain{
	{ChainID: 1, Name: "Ethereum Mainnet", Symbol: "ETH", RPCURL: "https://api.mycryptoapi.com/eth", ExplorerURL: "https://etherscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 8, Name: "Ubiq", Symbol: "UBQ", RPCURL: "https://rpc.octano.dev", ExplorerURL: "https://ubiqscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 30, Name: "Rootstock Mainnet", Symbol: "RBTC", RPCURL: "https://public-node.rsk.co", ExplorerURL: "https://explorer.rsk.co", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 56, Name: "BNB Smart Chain Mainnet", Symbol: "BNB", RPCURL: "https://bsc-dataseed1.bnbchain.org", ExplorerURL: "https://bscscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 60, Name: "GoChain", Symbol: "GO", RPCURL: "https://rpc.gochain.io", ExplorerURL: "https://explorer.gochain.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 61, Name: "Ethereum Classic", Symbol: "ETC", RPCURL: "https://etc.rivet.link", ExplorerURL: "https://etc.blockscout.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 70, Name: "Hoo Smart Chain", Symbol: "HOO", RPCURL: "https://http-mainnet.hoosmartchain.com", ExplorerURL: "https://www.hooscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 99, Name: "POA Network Core", Symbol: "POA", RPCURL: "https://core.poa.network", ExplorerURL: "https://blockscout.com/poa/core", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 100, Name: "Gnosis", Symbol: "XDAI", RPCURL: "https://rpc.gnosischain.com", ExplorerURL: "https://gnosisscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 108, Name: "ThunderCore Mainnet", Symbol: "TT", RPCURL: "https://mainnet-rpc.thundercore.com", ExplorerURL: "https://viewblock.io/thundercore", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 113, Name: "Dehvo", Symbol: "Deh", RPCURL: "https://connect.dehvo.com", ExplorerURL: "https://explorer.dehvo.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 121, Name: "Realchain Mainnet", Symbol: "REAL", RPCURL: "https://rcl-dataseed1.rclsidechain.com", ExplorerURL: "https://rclscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 126, Name: "OYchain Mainnet", Symbol: "OY", RPCURL: "https://rpc.mainnet.oychain.io", ExplorerURL: "https://explorer.oychain.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 128, Name: "Huobi ECO Chain Mainnet", Symbol: "HT", RPCURL: "https://http-mainnet.hecochain.com", ExplorerURL: "https://hecoinfo.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 137, Name: "Polygon Mainnet", Symbol: "POL", RPCURL: "https://polygon.drpc.org", ExplorerURL: "https://polygonscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 138, Name: "Defi Oracle Meta Mainnet", Symbol: "ETH", RPCURL: "https://rpc-http-pub.d-bis.org", ExplorerURL: "https://explorer.d-bis.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 143, Name: "Monad", Symbol: "MON", RPCURL: "https://rpc.monad.xyz", ExplorerURL: "https://monadvision.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 151, Name: "Redbelly Network Mainnet", Symbol: "RBNT", RPCURL: "https://governors.mainnet.redbelly.network", ExplorerURL: "https://redbelly.routescan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 166, Name: "Nomina", Symbol: "NOM", RPCURL: "https://mainnet.nomina.io", ExplorerURL: "https://nomscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 168, Name: "AIOZ Network", Symbol: "AIOZ", RPCURL: "https://eth-dataseed.aioz.network", ExplorerURL: "https://explorer.aioz.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 182, Name: "IOST Mainnet", Symbol: "BNB", RPCURL: "https://l2-mainnet.iost.io", ExplorerURL: "https://l2-scan.iost.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 204, Name: "opBNB Mainnet", Symbol: "BNB", RPCURL: "https://opbnb-mainnet-rpc.bnbchain.org", ExplorerURL: "https://mainnet.opbnbscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 239, Name: "TAC Mainnet", Symbol: "TAC", RPCURL: "https://rpc.tac.build", ExplorerURL: "https://explorer.tac.build", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 246, Name: "Energy Web Chain", Symbol: "EWT", RPCURL: "https://rpc.energyweb.org", ExplorerURL: "https://explorer.energyweb.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 269, Name: "High Performance Blockchain", Symbol: "HPB", RPCURL: "https://hpbnode.com", ExplorerURL: "https://hscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 273, Name: "XR One", Symbol: "XR1", RPCURL: "https://xr1.calderachain.xyz/http", ExplorerURL: "https://xr1.calderaexplorer.xyz", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 295, Name: "Hedera Mainnet", Symbol: "HBAR", RPCURL: "https://mainnet.hashio.io/api", ExplorerURL: "https://explorer.arkhia.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 314, Name: "Filecoin - Mainnet", Symbol: "FIL", RPCURL: "https://api.node.glif.io/", ExplorerURL: "https://filfox.info/en", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 321, Name: "KCC Mainnet", Symbol: "KCS", RPCURL: "https://rpc-mainnet.kcc.network", ExplorerURL: "https://explorer.kcc.io/en", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 369, Name: "PulseChain", Symbol: "PLS", RPCURL: "https://rpc.pulsechain.com", ExplorerURL: "https://ipfs.scan.pulsechain.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 480, Name: "World Chain", Symbol: "ETH", RPCURL: "https://worldchain-mainnet.g.alchemy.com/public", ExplorerURL: "https://worldscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 484, Name: "Camp Network Mainnet", Symbol: "CAMP", RPCURL: "https://rpc.camp.raas.gelato.cloud", ExplorerURL: "https://camp.cloud.blockscout.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 499, Name: "Rupaya", Symbol: "RUPX", RPCURL: "https://rpc.rupaya.io", ExplorerURL: "https://scan.rupaya.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 512, Name: "Double-A Chain Mainnet", Symbol: "AAC", RPCURL: "https://rpc.acuteangle.com", ExplorerURL: "https://scan.acuteangle.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 534, Name: "Candle", Symbol: "CNDL", RPCURL: "https://candle-rpc.com/", ExplorerURL: "https://candleexplorer.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 571, Name: "MetaChain Mainnet", Symbol: "MTC", RPCURL: "https://rpc.metatime.com", ExplorerURL: "https://explorer.metatime.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 686, Name: "Karura Network", Symbol: "KAR", RPCURL: "https://eth-rpc-karura.aca-api.network", ExplorerURL: "https://blockscout.karura.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 698, Name: "Matchain", Symbol: "BNB", RPCURL: "https://rpc.matchain.io", ExplorerURL: "https://matchscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 711, Name: "Tucana", Symbol: "TUC", RPCURL: "https://evm-rpc.tucana.zone", ExplorerURL: "https://explorer.tucana.zone", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 712, Name: "Birdee-2", Symbol: "TUC", RPCURL: "https://evm-rpc.birdee-2.tucana.zone", ExplorerURL: "https://explorer.birdee-2.tucana.zone", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 787, Name: "Acala Network", Symbol: "ACA", RPCURL: "https://eth-rpc-acala.aca-api.network", ExplorerURL: "https://blockscout.acala.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 813, Name: "Qitmeer Network Mainnet", Symbol: "MEER", RPCURL: "https://evm-dataseed1.meerscan.io", ExplorerURL: "https://qng.qitmeer.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 818, Name: "BeOne Chain Mainnet", Symbol: "BOC", RPCURL: "https://dataseed1.beonechain.com", ExplorerURL: "https://beonescan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 820, Name: "Callisto Mainnet", Symbol: "CLO", RPCURL: "https://rpc.callistodao.org", ExplorerURL: "https://explorer.callistodao.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 841, Name: "Taraxa Mainnet", Symbol: "TARA", RPCURL: "https://rpc.mainnet.taraxa.io/", ExplorerURL: "https://tara.to", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 888, Name: "Wanchain", Symbol: "WAN", RPCURL: "https://gwan-ssl.wandevs.org:56891/", ExplorerURL: "https://wanscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 917, Name: "Rinia", Symbol: "FIRE", RPCURL: "https://rinia-rpc1.thefirechain.com", ExplorerURL: "https://rinia.firescan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1009, Name: "Jumbochain Mainnet", Symbol: "JNFTC", RPCURL: "https://rpcpriv.jumbochain.org", ExplorerURL: "https://jumboscan.jumbochain.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1029, Name: "BitTorrent Chain Donau", Symbol: "BTT", RPCURL: "https://pre-rpc.bt.io", ExplorerURL: "https://testnet.bttcscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1134, Name: "StateMesh", Symbol: "MESH", RPCURL: "https://rpc.statemesh.net", ExplorerURL: "https://scan.statemesh.net", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1135, Name: "Lisk", Symbol: "ETH", RPCURL: "https://rpc.api.lisk.com", ExplorerURL: "https://blockscout.lisk.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1329, Name: "Sei Network", Symbol: "SEI", RPCURL: "https://evm-rpc.sei-apis.com", ExplorerURL: "https://seiscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1453, Name: "MetaChain Istanbul", Symbol: "MTC", RPCURL: "https://istanbul-rpc.metachain.dev", ExplorerURL: "https://istanbul-explorer.metachain.dev", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1456, Name: "ZKBase Mainnet", Symbol: "ETH", RPCURL: "https://mainnet-rpc.zkbase.app", ExplorerURL: "https://explorer.zkbase.app", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1689, Name: "NERO Mainnet", Symbol: "NERO", RPCURL: "https://rpc.nerochain.io", ExplorerURL: "https://www.neroscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1776, Name: "Injective", Symbol: "INJ", RPCURL: "https://sentry.evm-rpc.injective.network", ExplorerURL: "https://blockscout.injective.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1804, Name: "Kerleano", Symbol: "CRC", RPCURL: "https://rpc1.kerleano.ca-dag.work", ExplorerURL: "https://ethereum-pocr.github.io/explorer/kerleano", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1818, Name: "Cube Chain Mainnet", Symbol: "CUBE", RPCURL: "https://http-mainnet.cube.network", ExplorerURL: "https://cubescan.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1821, Name: "Ruby Smart Chain MAINNET", Symbol: "RUBY", RPCURL: "https://mainnet-data.rubychain.io/", ExplorerURL: "https://rubyscan.net", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1829, Name: "PlayBlock", Symbol: "PBG", RPCURL: "https://rpc.playblock.io", ExplorerURL: "https://explorer.playblock.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1848, Name: "Swisstronik Mainnet", Symbol: "SWTR", RPCURL: "https://json-rpc.mainnet.swisstronik.com/unencrypted/", ExplorerURL: "https://explorer-evm.mainnet.swisstronik.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1899, Name: "ReDeFi Layer 2", Symbol: "RED", RPCURL: "https://layer2.redefi.world", ExplorerURL: "https://scanlayer2.redefi.world", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1967, Name: "Eleanor", Symbol: "MTC", RPCURL: "https://rpc.metatime.com/eleanor", ExplorerURL: "https://explorer.metatime.com/eleanor", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1997, Name: "Kyoto", Symbol: "KYOTO", RPCURL: "https://rpc.kyotochain.io", ExplorerURL: "https://kyotoscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2017, Name: "Adiri", Symbol: "TEL", RPCURL: "https://rpc.telcoin.network", ExplorerURL: "https://telscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2021, Name: "Edgeware EdgeEVM Mainnet", Symbol: "EDG", RPCURL: "https://edgeware-evm.jelliedowl.net", ExplorerURL: "https://edgscan.live", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2025, Name: "Rangers Protocol Mainnet", Symbol: "RPG", RPCURL: "https://mainnet.rangersprotocol.com/api/jsonrpc", ExplorerURL: "https://scan.rangersprotocol.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2049, Name: "Movo Smart Chain Mainnet", Symbol: "MOVO", RPCURL: "https://msc-rpc.movoscan.com", ExplorerURL: "https://movoscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2109, Name: "Exosama Network", Symbol: "SAMA", RPCURL: "https://rpc.exosama.com", ExplorerURL: "https://explorer.exosama.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2199, Name: "Moonsama Network", Symbol: "SAMA", RPCURL: "https://rpc.moonsama.com", ExplorerURL: "https://explorer.moonsama.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2366, Name: "KiteAI", Symbol: "KITE", RPCURL: "https://rpc.gokite.ai", ExplorerURL: "https://kitescan.ai", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2390, Name: "TAC Turin", Symbol: "TAC", RPCURL: "https://turin.rpc.tac.build", ExplorerURL: "https://turin.explorer.tac.build", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2391, Name: "TAC Saint Petersburg", Symbol: "TAC", RPCURL: "https://spb.rpc.tac.build", ExplorerURL: "https://spb.explorer.tac.build", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2425, Name: "King Of Legends Mainnet", Symbol: "KCC", RPCURL: "https://rpc-mainnet.kinggamer.org/", ExplorerURL: "https://kingscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2440, Name: "Atleta Network", Symbol: "ATLA", RPCURL: "https://rpc.mainnet.atleta.network", ExplorerURL: "https://blockscout.atleta.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2748, Name: "Nanon", Symbol: "ETH", RPCURL: "https://rpc.nanon.network", ExplorerURL: "https://explorer.nanon.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 2818, Name: "Morph", Symbol: "ETH", RPCURL: "https://rpc.morphl2.io", ExplorerURL: "https://explorer.morphl2.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 3111, Name: "Alpha Chain Mainnet", Symbol: "ETH", RPCURL: "https://rpc.goalpha.org", ExplorerURL: "https://scan.goalpha.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 3490, Name: "GTCSCAN", Symbol: "GTC", RPCURL: "https://gtc-dataseed.gtcscan.io/", ExplorerURL: "https://gtcscan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 4003, Name: "X1 Fastnet", Symbol: "XN", RPCURL: "https://x1-fastnet.xen.network", ExplorerURL: "https://explorer.x1-fastnet.xen.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 4158, Name: "CrossFi Mainnet", Symbol: "XFI", RPCURL: "https://rpc.mainnet.ms/", ExplorerURL: "https://xfiscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 4242, Name: "Nexi Mainnet", Symbol: "NEXI", RPCURL: "https://rpc.chain.nexi.technology/", ExplorerURL: "https://www.nexiscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 4243, Name: "Nexi V2 Mainnet", Symbol: "NEXI", RPCURL: "https://chain.nexiv2.nexilix.com", ExplorerURL: "https://www.nexiscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 4646, Name: "MST Mainnet", Symbol: "MSTC", RPCURL: "https://mariorpc.mstblockchain.com", ExplorerURL: "https://mstscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 5232, Name: "LiterMark Chain", Symbol: "LMK", RPCURL: "https://litermark.org/rpc", ExplorerURL: "https://litermark.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 5330, Name: "Superseed", Symbol: "ETH", RPCURL: "https://mainnet.superseed.xyz", ExplorerURL: "https://explorer.superseed.xyz", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 5424, Name: "edeXa Mainnet", Symbol: "EDX", RPCURL: "https://rpc.edexa.network", ExplorerURL: "https://explorer.edexa.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 5888, Name: "MANTRA Chain", Symbol: "MANTRA", RPCURL: "https://evm.mantrachain.io", ExplorerURL: "https://blockscout.mantrascan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 6278, Name: "Rails", Symbol: "STEAMX", RPCURL: "https://mainnet.steamexchange.io", ExplorerURL: "https://explore.steamexchange.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 6322, Name: "Aura Mainnet", Symbol: "AURA", RPCURL: "https://jsonrpc.aura.network", ExplorerURL: "https://aurascan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 6779, Name: "Compverse Mainnet", Symbol: "CPV", RPCURL: "https://rpc.compverse.io/", ExplorerURL: "https://scan.compverse.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 6805, Name: "RACE Mainnet", Symbol: "ETH", RPCURL: "https://racemainnet.io/", ExplorerURL: "https://racescan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 6868, Name: "Pools Mainnet", Symbol: "POOLS", RPCURL: "https://rpc.poolsmobility.com", ExplorerURL: "https://scan.poolsmobility.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 6941, Name: "Monolythium", Symbol: "LYTH", RPCURL: "https://evm.mainnet.mononodes.xyz", ExplorerURL: "https://monoscan.xyz", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 7341, Name: "Shyft Mainnet", Symbol: "SHYFT", RPCURL: "https://rpc.shyft.network/", ExplorerURL: "https://bx.shyft.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 7778, Name: "Orenium Mainnet Protocol", Symbol: "ORE", RPCURL: "https://validator-mainnet.orenium.org", ExplorerURL: "https://oreniumscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 7897, Name: "arena-z", Symbol: "ETH", RPCURL: "https://rpc.arena-z.gg", ExplorerURL: "https://explorer.arena-z.gg", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 8017, Name: "iSunCoin Mainnet", Symbol: "ISC", RPCURL: "https://mainnet.isuncoin.com", ExplorerURL: "https://baifa.io/app/chains/8017", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 8047, Name: "BOAT Mainnet", Symbol: "BOAT", RPCURL: "https://rpc0.come.boat/", ExplorerURL: "https://scan.come.boats", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 8217, Name: "Kaia Mainnet", Symbol: "KAIA", RPCURL: "https://public-en.node.kaia.io", ExplorerURL: "https://kaiascope.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 8723, Name: "TOOL Global Mainnet", Symbol: "OLO", RPCURL: "https://mainnet-web3.wolot.io", ExplorerURL: "https://www.olo.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 8732, Name: "Bullions Smart Chain", Symbol: "BLN", RPCURL: "https://rpc.bullionsx.org", ExplorerURL: "https://bullionscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 9898, Name: "Larissa Chain", Symbol: "LRS", RPCURL: "https://rpc.larissa.network", ExplorerURL: "https://scan.larissa.network", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 9922, Name: "JingleX L2", Symbol: "JNX", RPCURL: "https://rpc.jinglex.net", ExplorerURL: "https://jinglex.net/explorer", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 9982, Name: "MFEV CHAIN MAINNET", Symbol: "MFEV", RPCURL: "https://rpc.mfevscan.com", ExplorerURL: "https://mfevscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 18888, Name: "Titan (TKX)", Symbol: "TKX", RPCURL: "https://titan-json-rpc.titanlab.io", ExplorerURL: "https://tkxscan.io/Titan", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 30088, Name: "MiYou Mainnet", Symbol: "MY", RPCURL: "https://blockchain.miyou.io", ExplorerURL: "https://myscan.miyou.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 36969, Name: "AMA Mainnet", Symbol: "AMA", RPCURL: "https://mainnet-rpc.ama.one", ExplorerURL: "https://ama-explorer.ddns.net", Decimals: 9, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 43114, Name: "Avalanche C-Chain", Symbol: "AVAX", RPCURL: "https://api.avax.network/ext/bc/C/rpc", ExplorerURL: "https://snowscan.xyz", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 43522, Name: "Insectarium", Symbol: "M", RPCURL: "https://rpc.insectarium.memecore.net", ExplorerURL: "https://insectarium.memecorescan.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 77001, Name: "BORAchain mainnet", Symbol: "BORA", RPCURL: "https://public-node.api.boraportal.com/bora/mainnet", ExplorerURL: "https://scope.boraportal.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 84841, Name: "O Chain", Symbol: "O", RPCURL: "https://rpc.o.xyz", ExplorerURL: "https://explorer.o.xyz", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 96370, Name: "Lumoz Chain Mainnet", Symbol: "MOZ", RPCURL: "https://rpc.lumoz.org", ExplorerURL: "https://scan.lumoz.info", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 111188, Name: "re.al", Symbol: "reETH", RPCURL: "https://rpc.realforreal.gelato.digital", ExplorerURL: "https://explorer.re.al", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 200901, Name: "Bitlayer Mainnet", Symbol: "BTC", RPCURL: "https://rpc.bitlayer.org", ExplorerURL: "https://www.btrscan.com", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 955305, Name: "Eluvio Content Fabric", Symbol: "ELV", RPCURL: "https://host-76-74-28-226.contentfabric.io/eth/", ExplorerURL: "https://explorer.eluv.io", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 65000000, Name: "Autonity Mainnet", Symbol: "ATN", RPCURL: "https://rpc.autonity-apis.com", ExplorerURL: "https://autonityscan.org", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 728126428, Name: "Tron Mainnet", Symbol: "TRX", RPCURL: "https://rpc.ankr.com/tron_jsonrpc", ExplorerURL: "https://tronscan.org", Decimals: 6, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1666600000, Name: "Harmony Mainnet Shard 0", Symbol: "ONE", RPCURL: "https://api.harmony.one", ExplorerURL: "https://explorer.harmony.one", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
	{ChainID: 1666600001, Name: "Harmony Mainnet Shard 1", Symbol: "ONE", RPCURL: "https://api.s1.t.hmny.io", ExplorerURL: "https://explorer.harmony.one/blocks/shard/1", Decimals: 18, DerivationPath: "m/44'/60'/0'/0/0"},
}

// defaultNonEVMChains returns the 66 canonical non-EVM mainnet chains.
var defaultNonEVMChains = []defaultChain{
	{ChainID: 9000000000, Name: "Bitcoin", Symbol: "BTC", RPCURL: "https://blockstream.info/api", ExplorerURL: "https://mempool.space", Decimals: 8, DerivationPath: "m/44'/0'/0'/0/0", ChainType: "bitcoin"},
	{ChainID: 9000000002, Name: "Litecoin", Symbol: "LTC", RPCURL: "https://litecoinspace.org/api", ExplorerURL: "https://blockchair.com/litecoin", Decimals: 8, DerivationPath: "m/44'/2'/0'/0/0", ChainType: "litecoin"},
	{ChainID: 9000000003, Name: "Dogecoin", Symbol: "DOGE", RPCURL: "https://dogechain.info/api/v1", ExplorerURL: "https://blockchair.com/dogecoin", Decimals: 8, DerivationPath: "m/44'/3'/0'/0/0", ChainType: "dogecoin"},
	{ChainID: 9000000005, Name: "Dash", Symbol: "DASH", RPCURL: "https://insight.dash.org/insight-api", ExplorerURL: "https://blockchair.com/dash", Decimals: 8, DerivationPath: "m/44'/5'/0'/0/0", ChainType: "dash"},
	{ChainID: 9000000145, Name: "Bitcoin Cash", Symbol: "BCH", RPCURL: "https://api.blockchair.com/bitcoin-cash", ExplorerURL: "https://blockchair.com/bitcoin-cash", Decimals: 8, DerivationPath: "m/44'/145'/0'/0/0", ChainType: "bitcoincash"},
	{ChainID: 9000000236, Name: "Bitcoin SV", Symbol: "BSV", RPCURL: "https://api.blockchair.com/bitcoin-sv", ExplorerURL: "https://blockchair.com/bitcoin-sv", Decimals: 8, DerivationPath: "m/44'/236'/0'/0/0", ChainType: "bitcoinsv"},
	{ChainID: 9000000899, Name: "eCash", Symbol: "XEC", RPCURL: "https://explorer.e.cash/api", ExplorerURL: "https://explorer.e.cash", Decimals: 2, DerivationPath: "m/44'/899'/0'/0/0", ChainType: "ecash"},
	{ChainID: 9000000175, Name: "Ravencoin", Symbol: "RVN", RPCURL: "https://ravencoin.network/api", ExplorerURL: "https://ravencoin.network", Decimals: 8, DerivationPath: "m/44'/175'/0'/0/0", ChainType: "raven"},
	{ChainID: 9000000133, Name: "Zcash", Symbol: "ZEC", RPCURL: "https://lwdv3.zecwallet.co", ExplorerURL: "https://blockchair.com/zcash", Decimals: 8, DerivationPath: "m/44'/133'/0'/0/0", ChainType: "zcash"},
	{ChainID: 9000000017, Name: "Groestlcoin", Symbol: "GRS", RPCURL: "https://groestlsight.groestlcoin.org/api", ExplorerURL: "https://groestlsight.groestlcoin.org", Decimals: 8, DerivationPath: "m/44'/17'/0'/0/0", ChainType: "groestlcoin"},
	{ChainID: 9000000020, Name: "DigiByte", Symbol: "DGB", RPCURL: "https://digiexplorer.info/api/v2", ExplorerURL: "https://digiexplorer.info", Decimals: 8, DerivationPath: "m/44'/20'/0'/0/0", ChainType: "digibyte"},
	{ChainID: 9000002301, Name: "Qtum", Symbol: "QTUM", RPCURL: "https://qtum.info/api", ExplorerURL: "https://qtum.info", Decimals: 8, DerivationPath: "m/44'/2301'/0'/0/0", ChainType: "qtum"},
	{ChainID: 9000000077, Name: "Verge", Symbol: "XVG", RPCURL: "https://api.vergecurrency.network", ExplorerURL: "https://verge-blockchain.info", Decimals: 6, DerivationPath: "m/44'/77'/0'/0/0", ChainType: "verge"},
	{ChainID: 9000000007, Name: "Namecoin", Symbol: "NMC", RPCURL: "https://namecoin.info/api", ExplorerURL: "https://namecoin.info", Decimals: 8, DerivationPath: "m/44'/7'/0'/0/0", ChainType: "namecoin"},
	{ChainID: 9000000022, Name: "Monacoin", Symbol: "MONA", RPCURL: "https://mona.chainsight.info/api", ExplorerURL: "https://mona.chainsight.info", Decimals: 8, DerivationPath: "m/44'/22'/0'/0/0", ChainType: "monacoin"},
	{ChainID: 9000000010, Name: "BlackCoin", Symbol: "BLK", RPCURL: "https://cryptoid.info/blk/api", ExplorerURL: "https://chainz.cryptoid.org/blk", Decimals: 8, DerivationPath: "m/44'/10'/0'/0/0", ChainType: "blackcoin"},
	{ChainID: 9000000141, Name: "Komodo", Symbol: "KMD", RPCURL: "https://kmdexplorer.io/api", ExplorerURL: "https://kmdexplorer.io", Decimals: 8, DerivationPath: "m/44'/141'/0'/0/0", ChainType: "komodo"},
	{ChainID: 9000000501, Name: "Solana", Symbol: "SOL", RPCURL: "https://api.mainnet-beta.solana.com", ExplorerURL: "https://solscan.io", Decimals: 9, DerivationPath: "m/44'/501'/0'/0'/0'", ChainType: "solana"},
	{ChainID: 9000000637, Name: "Aptos", Symbol: "APT", RPCURL: "https://fullnode.mainnet.aptoslabs.com", ExplorerURL: "https://aptoscan.com", Decimals: 8, DerivationPath: "m/44'/637'/0'/0/0", ChainType: "aptos"},
	{ChainID: 9000000784, Name: "Sui", Symbol: "SUI", RPCURL: "https://fullnode.mainnet.sui.io", ExplorerURL: "https://suiscan.xyz", Decimals: 9, DerivationPath: "m/44'/784'/0'/0/0", ChainType: "sui"},
	{ChainID: 9000000607, Name: "TON", Symbol: "TON", RPCURL: "https://toncenter.com/api/v2/jsonRPC", ExplorerURL: "https://tonscan.org", Decimals: 9, DerivationPath: "m/44'/607'/0'/0/0", ChainType: "ton"},
	{ChainID: 9000000118, Name: "Cosmos Hub", Symbol: "ATOM", RPCURL: "https://rpc.cosmos.directory/cosmoshub", ExplorerURL: "https://www.mintscan.io/cosmos", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000000529, Name: "Secret Network", Symbol: "SCRT", RPCURL: "https://rpc.cosmos.directory/secret", ExplorerURL: "https://www.mintscan.io/secret", Decimals: 6, DerivationPath: "m/44'/529'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000000330, Name: "Terra Classic", Symbol: "LUNC", RPCURL: "https://terra-classic-rpc.publicnode.com", ExplorerURL: "https://finder.terra.money/classic", Decimals: 6, DerivationPath: "m/44'/330'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000073068, Name: "Injective", Symbol: "INJ", RPCURL: "https://injective-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/injective", Decimals: 18, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000014648, Name: "Celestia", Symbol: "TIA", RPCURL: "https://celestia-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/celestia", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000026317, Name: "Osmosis", Symbol: "OSMO", RPCURL: "https://osmosis-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/osmosis", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000049823, Name: "dYdX", Symbol: "DYDX", RPCURL: "https://dydx-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/dydx", Decimals: 18, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000073741, Name: "Sei", Symbol: "SEI", RPCURL: "https://sei-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/sei", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000041857, Name: "Kujira", Symbol: "KUJI", RPCURL: "https://kujira-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/kujira", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000012099, Name: "Stride", Symbol: "STRD", RPCURL: "https://stride-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/stride", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000090063, Name: "Neutron", Symbol: "NTRN", RPCURL: "https://neutron-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/neutron", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000005267, Name: "Juno", Symbol: "JUNO", RPCURL: "https://juno-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/juno", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000007183, Name: "Akash", Symbol: "AKT", RPCURL: "https://akash-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/akash", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000018759, Name: "Persistence", Symbol: "XPRT", RPCURL: "https://persistence-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/persistence", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000034677, Name: "Evmos (cosmos)", Symbol: "EVMOS", RPCURL: "https://evmos-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/evmos", Decimals: 18, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000054841, Name: "Canto (cosmos)", Symbol: "CANTO", RPCURL: "https://canto-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/canto", Decimals: 18, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000003318, Name: "Kava (cosmos)", Symbol: "KAVA", RPCURL: "https://kava-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/kava", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000062954, Name: "Cronos (cosmos)", Symbol: "CRO", RPCURL: "https://cronos-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/cronos", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000016892, Name: "Stargaze", Symbol: "STARS", RPCURL: "https://stargaze-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/stargaze", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000021252, Name: "Saga", Symbol: "SAGA", RPCURL: "https://saga-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/saga", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000086660, Name: "Noble", Symbol: "USDC", RPCURL: "https://noble-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/noble", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000040572, Name: "Axelar", Symbol: "AXL", RPCURL: "https://axelar-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/axelar", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000007153, Name: "UMEE", Symbol: "UMEE", RPCURL: "https://umee-rpc.publicnode.com", ExplorerURL: "https://www.mintscan.io/umee", Decimals: 6, DerivationPath: "m/44'/118'/0'/0/0", ChainType: "cosmos"},
	{ChainID: 9000000354, Name: "Polkadot", Symbol: "DOT", RPCURL: "https://rpc.polkadot.io", ExplorerURL: "https://polkadot.subscan.io", Decimals: 10, DerivationPath: "m/44'/354'/0'/0/0", ChainType: "polkadot"},
	{ChainID: 9000000434, Name: "Kusama", Symbol: "KSM", RPCURL: "https://kusama-rpc.polkadot.io", ExplorerURL: "https://kusama.subscan.io", Decimals: 12, DerivationPath: "m/44'/434'/0'/0/0", ChainType: "polkadot"},
	{ChainID: 9000000397, Name: "NEAR", Symbol: "NEAR", RPCURL: "https://rpc.mainnet.near.org", ExplorerURL: "https://nearblocks.io", Decimals: 24, DerivationPath: "m/44'/397'/0'/0/0", ChainType: "near"},
	{ChainID: 9000000283, Name: "Algorand", Symbol: "ALGO", RPCURL: "https://mainnet-api.algonode.cloud", ExplorerURL: "https://lora.algokit.io/mainnet", Decimals: 6, DerivationPath: "m/44'/283'/0'/0/0", ChainType: "algorand"},
	{ChainID: 9000001815, Name: "Cardano", Symbol: "ADA", RPCURL: "https://cardano-mainnet.blockfrost.io/api/v0", ExplorerURL: "https://cardanoscan.io", Decimals: 6, DerivationPath: "m/1852'/1815'/0'/0/0", ChainType: "cardano"},
	{ChainID: 9000000144, Name: "XRP Ledger", Symbol: "XRP", RPCURL: "https://xrplcluster.com", ExplorerURL: "https://livenet.xrpl.org", Decimals: 6, DerivationPath: "m/44'/144'/0'/0/0", ChainType: "ripple"},
	{ChainID: 9000000148, Name: "Stellar", Symbol: "XLM", RPCURL: "https://horizon.stellar.org", ExplorerURL: "https://stellar.expert/explorer/public", Decimals: 7, DerivationPath: "m/44'/148'/0'/0/0", ChainType: "stellar"},
	{ChainID: 9000003030, Name: "Hedera", Symbol: "HBAR", RPCURL: "https://mainnet.mirrornode.hedera.com", ExplorerURL: "https://hashscan.io/mainnet", Decimals: 8, DerivationPath: "m/44'/3030'/0'/0/0", ChainType: "hedera"},
	{ChainID: 9000001729, Name: "Tezos", Symbol: "XTZ", RPCURL: "https://mainnet.api.tez.ie", ExplorerURL: "https://tzkt.io", Decimals: 6, DerivationPath: "m/44'/1729'/0'/0/0", ChainType: "tezos"},
	{ChainID: 9000000539, Name: "Flow", Symbol: "FLOW", RPCURL: "https://rest-mainnet.onflow.org", ExplorerURL: "https://flowscan.org", Decimals: 8, DerivationPath: "m/44'/539'/0'/0/0", ChainType: "flow"},
	{ChainID: 9000111111, Name: "Kaspa", Symbol: "KAS", RPCURL: "https://api.kaspa.org", ExplorerURL: "https://kaspa.fyi", Decimals: 2, DerivationPath: "m/44'/111111'/0'/0/0", ChainType: "kaspa"},
	{ChainID: 9000000165, Name: "Nano", Symbol: "XNO", RPCURL: "https://node.somenano.com/api", ExplorerURL: "https://nanolooker.com", Decimals: 30, DerivationPath: "m/44'/165'/0'/0/0", ChainType: "nano"},
	{ChainID: 9000000195, Name: "Tron", Symbol: "TRX", RPCURL: "https://api.trongrid.io", ExplorerURL: "https://tronscan.org", Decimals: 6, DerivationPath: "m/44'/195'/0'/0/0", ChainType: "tron"},
	{ChainID: 9000000818, Name: "VeChain", Symbol: "VET", RPCURL: "https://mainnet.vechain.org", ExplorerURL: "https://explore.vechain.org", Decimals: 18, DerivationPath: "m/44'/818'/0'/0/0", ChainType: "vechain"},
	{ChainID: 9005741564, Name: "Waves", Symbol: "WAVES", RPCURL: "https://nodes.wavesnodes.com", ExplorerURL: "https://wavesexplorer.com", Decimals: 8, DerivationPath: "m/44'/5741564'/0'/0/0", ChainType: "waves"},
	{ChainID: 9000000508, Name: "Elrond", Symbol: "EGLD", RPCURL: "https://api.elrond.com", ExplorerURL: "https://explorer.multiversx.com", Decimals: 18, DerivationPath: "m/44'/508'/0'/0/0", ChainType: "elrond"},
	{ChainID: 9000000313, Name: "Zilliqa", Symbol: "ZIL", RPCURL: "https://api.zilliqa.com", ExplorerURL: "https://devex.zilliqa.com", Decimals: 12, DerivationPath: "m/44'/313'/0'/0/0", ChainType: "zilliqa"},
	{ChainID: 9000000461, Name: "Filecoin", Symbol: "FIL", RPCURL: "https://api.node.glif.io/rpc/v0", ExplorerURL: "https://filfox.info/en", Decimals: 18, DerivationPath: "m/44'/461'/0'/0/0", ChainType: "filecoin"},
	{ChainID: 9000000223, Name: "Internet Computer", Symbol: "ICP", RPCURL: "https://ic0.app/api", ExplorerURL: "https://dashboard.internetcomputer.org", Decimals: 8, DerivationPath: "m/44'/223'/0'/0/0", ChainType: "internetcomputer"},
	{ChainID: 9000042554, Name: "Aleo", Symbol: "ALEO", RPCURL: "https://api.aleo.network", ExplorerURL: "https://explorer.aleo.org", Decimals: 6, DerivationPath: "m/44'/42554'/0'/0/0", ChainType: "aleo"},
	{ChainID: 9000000309, Name: "Nervos CKB", Symbol: "CKB", RPCURL: "https://mainnet.ckb.dev/rpc", ExplorerURL: "https://explorer.nervos.org", Decimals: 8, DerivationPath: "m/44'/309'/0'/0/0", ChainType: "nervos"},
	{ChainID: 9000004242, Name: "Pi Network", Symbol: "PI", RPCURL: "", ExplorerURL: "https://blockexplorer.minepi.com", Decimals: 8, DerivationPath: "m/44'/4242'/0'/0/0", ChainType: "pi"},
}
