# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'TigerWallet' do
  # Networking
  pod 'Alamofire', '~> 5.8'
  pod 'Moya', '~> 15.0'
  
  # Web3
  pod 'web3swift', '~> 3.2'
  pod 'WalletConnect', '~> 1.8'
  
  # Storage
  pod 'KeychainAccess', '~> 4.2'
  
  # UI
  pod 'SnapKit', '~> 5.6'
  pod 'Kingfisher', '~> 7.10'
  pod 'SkeletonView', '~> 1.30'
  
  # Security
  pod 'CryptoSwift', '~> 1.8'
  
  # Charts
  pod 'Charts', '~> 5.0'
  
  # QR Code
  pod 'EFQRCode', '~> 6.1'
  
  # Biometric
  pod 'LocalAuthentication', :modular_headers => true
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
