package main

import (
	"fmt"
)

// ChainConfig describes a supported blockchain (EVM or non-EVM) and its
// derivation path. EVM chains (Type=="evm") are usable for full wallet
// operations (RPC, balance, signing, broadcast); non-EVM chains are
// registered for discovery and address derivation only — on-chain
// operations for them require their dedicated SDK services.
type ChainConfig struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Symbol         string `json:"symbol"`
	Type           string `json:"type"` // evm, solana, bitcoin, tron, cosmos, near, aptos, sui, etc.
	RPCEndpoint    string `json:"rpc_endpoint"`
	DerivationPath string `json:"derivation_path"`
	ExplorerAPI    string `json:"explorer_api"`
	ExplorerURL    string `json:"explorer_url"`
	Decimals       int    `json:"decimals"`
	CoinGeckoID    string `json:"coingecko_id"`
	AddressPrefix  string `json:"address_prefix,omitempty"`
	IsEVM          bool   `json:"is_evm"`
}

// SupportedChains is the canonical chain registry: 100 EVM mainnet +
// 50 non-EVM chains (incl. Pi Network). ALL mainnet, no testnets.
// RPC endpoints are public community endpoints; override via env
// CHAIN_<ID>_RPC / CHAIN_<ID>_EXPLORER for production. Admins can add
// more chains at runtime via the admin_chain_config PostgreSQL table
// (see admin_ext.go).
var SupportedChains = map[int64]ChainConfig{
	1: {
		ID: 1, Name: "Ethereum", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://eth.llamarpc.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.etherscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	56: {
		ID: 56, Name: "BNB Smart Chain", Symbol: "BNB", Type: "evm",
		RPCEndpoint:    "https://bsc-dataseed.binance.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.bscscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "binancecoin",
		IsEVM: true,
	},
	137: {
		ID: 137, Name: "Polygon", Symbol: "MATIC", Type: "evm",
		RPCEndpoint:    "https://polygon-rpc.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.polygonscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "matic-network",
		IsEVM: true,
	},
	42161: {
		ID: 42161, Name: "Arbitrum One", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://arb1.arbitrum.io/rpc",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.arbiscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	10: {
		ID: 10, Name: "Optimism", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://mainnet.optimism.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api-optimistic.etherscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	8453: {
		ID: 8453, Name: "Base", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://mainnet.base.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.basescan.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	43114: {
		ID: 43114, Name: "Avalanche C-Chain", Symbol: "AVAX", Type: "evm",
		RPCEndpoint:    "https://api.avax.network/ext/bc/C/rpc",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.snowtrace.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "avalanche-2",
		IsEVM: true,
	},
	250: {
		ID: 250, Name: "Fantom", Symbol: "FTM", Type: "evm",
		RPCEndpoint:    "https://rpc.fantom.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.ftmscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "fantom",
		IsEVM: true,
	},
	25: {
		ID: 25, Name: "Cronos", Symbol: "CRO", Type: "evm",
		RPCEndpoint:    "https://evm.cronos.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.cronoscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "crypto-com-chain",
		IsEVM: true,
	},
	42220: {
		ID: 42220, Name: "Celo", Symbol: "CELO", Type: "evm",
		RPCEndpoint:    "https://forno.celo.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.celo.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "celo",
		IsEVM: true,
	},
	1284: {
		ID: 1284, Name: "Moonbeam", Symbol: "GLMR", Type: "evm",
		RPCEndpoint:    "https://rpc.api.moonbeam.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api-moonbeam.moonscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "moonbeam",
		IsEVM: true,
	},
	1285: {
		ID: 1285, Name: "Moonriver", Symbol: "MOVR", Type: "evm",
		RPCEndpoint:    "https://rpc.api.moonriver.moonbeam.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api-moonriver.moonscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "moonriver",
		IsEVM: true,
	},
	592: {
		ID: 592, Name: "Astar", Symbol: "ASTR", Type: "evm",
		RPCEndpoint:    "https://evm.astar.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://blockscout.com/astar/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "astar",
		IsEVM: true,
	},
	336: {
		ID: 336, Name: "Shiden", Symbol: "SDN", Type: "evm",
		RPCEndpoint:    "https://evm.shiden.astar.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://blockscout.com/shiden/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "shiden",
		IsEVM: true,
	},
	7700: {
		ID: 7700, Name: "Canto", Symbol: "CANTO", Type: "evm",
		RPCEndpoint:    "https://canto.gravitychain.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://evm.explorer.canto.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "canto",
		IsEVM: true,
	},
	5000: {
		ID: 5000, Name: "Mantle", Symbol: "MNT", Type: "evm",
		RPCEndpoint:    "https://rpc.mantle.xyz",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.mantle.xyz/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "mantle",
		IsEVM: true,
	},
	534352: {
		ID: 534352, Name: "Scroll", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.scroll.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.scrollscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	324: {
		ID: 324, Name: "zkSync Era", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://mainnet.era.zksync.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://block-explorer-api.mainnet.zksync.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	59144: {
		ID: 59144, Name: "Linea", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.linea.build",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.lineascan.build/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	1101: {
		ID: 1101, Name: "Polygon zkEVM", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://zkevm-rpc.polygon.technology",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api-zkevm.polygonscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	204: {
		ID: 204, Name: "opBNB", Symbol: "BNB", Type: "evm",
		RPCEndpoint:    "https://opbnb-rpc.publicnode.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api-opbnb.bscscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "binancecoin",
		IsEVM: true,
	},
	1666600000: {
		ID: 1666600000, Name: "Harmony", Symbol: "ONE", Type: "evm",
		RPCEndpoint:    "https://api.harmony.one",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.harmony.one/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "harmony",
		IsEVM: true,
	},
	2222: {
		ID: 2222, Name: "Kava EVM", Symbol: "KAVA", Type: "evm",
		RPCEndpoint:    "https://evm.kava.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://kava.evmos.dev/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "kava",
		IsEVM: true,
	},
	369: {
		ID: 369, Name: "PulseChain", Symbol: "PLS", Type: "evm",
		RPCEndpoint:    "https://rpc.pulsechain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://scan.pulsechain.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "pulsechain",
		IsEVM: true,
	},
	288: {
		ID: 288, Name: "Boba Network", Symbol: "BOBA", Type: "evm",
		RPCEndpoint:    "https://mainnet.boba.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://blockexplorer.boba.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "boba-network",
		IsEVM: true,
	},
	42170: {
		ID: 42170, Name: "Arbitrum Nova", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://nova.arbitrum.io/rpc",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api-nova.arbiscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	314: {
		ID: 314, Name: "Filecoin FEVM", Symbol: "FIL", Type: "evm",
		RPCEndpoint:    "https://api.filecoin.space",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://filfox.info/api/v1", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "filecoin",
		IsEVM: true,
	},
	7777777: {
		ID: 7777777, Name: "Zora", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.zora.energy",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.zora.energy/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	1699: {
		ID: 1699, Name: "Manta Pacific", Symbol: "MANTA", Type: "evm",
		RPCEndpoint:    "https://pacific-rpc.manta.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://pacific-explorer.manta.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "manta-network",
		IsEVM: true,
	},
	34443: {
		ID: 34443, Name: "Mode", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://mainnet.mode.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.mode.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	5002: {
		ID: 5002, Name: "Fraxtal", Symbol: "FRAX", Type: "evm",
		RPCEndpoint:    "https://rpc.frax.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.fraxscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "frax-share",
		IsEVM: true,
	},
	8888888: {
		ID: 8888888, Name: "Viction", Symbol: "VIC", Type: "evm",
		RPCEndpoint:    "https://rpc.viction.xyz",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://www.vicscan.xyz/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "tomochain",
		IsEVM: true,
	},
	2020: {
		ID: 2020, Name: "Ronin", Symbol: "RON", Type: "evm",
		RPCEndpoint:    "https://api.roninchain.com/rpc",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.roninchain.com", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ronin",
		IsEVM: true,
	},
	42262: {
		ID: 42262, Name: "Oasis Emerald", Symbol: "ROSE", Type: "evm",
		RPCEndpoint:    "https://emerald.oasis.dev",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.emerald.oasis.dev/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "oasis-network",
		IsEVM: true,
	},
	9001: {
		ID: 9001, Name: "Evmos", Symbol: "EVMOS", Type: "evm",
		RPCEndpoint:    "https://evmos-rpc.publicnode.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://evm.evmos.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "evmos",
		IsEVM: true,
	},
	321: {
		ID: 321, Name: "KCC", Symbol: "KCS", Type: "evm",
		RPCEndpoint:    "https://rpc.kcc.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.kcc.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "kucoin-shares",
		IsEVM: true,
	},
	2000: {
		ID: 2000, Name: "Dogechain", Symbol: "DC", Type: "evm",
		RPCEndpoint:    "https://rpc.dogechain.dog",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.dogechain.dog/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "dogechain",
		IsEVM: true,
	},
	2001: {
		ID: 2001, Name: "Milkomeda Cardano", Symbol: "ADA", Type: "evm",
		RPCEndpoint:    "https://rpc-mainnet-cardano-evm.c1.milkomeda.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer-mainnet-cardano-evm.c1.milkomeda.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "cardano",
		IsEVM: true,
	},
	57: {
		ID: 57, Name: "Syscoin", Symbol: "SYS", Type: "evm",
		RPCEndpoint:    "https://rpc.syscoin.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.syscoin.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "syscoin",
		IsEVM: true,
	},
	1890: {
		ID: 1890, Name: "Lightlink", Symbol: "LGT", Type: "evm",
		RPCEndpoint:    "https://replicator-01.lightlink.io/rpc/v1",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.lightlink.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "lightlink",
		IsEVM: true,
	},
	81457: {
		ID: 81457, Name: "Berachain", Symbol: "BERA", Type: "evm",
		RPCEndpoint:    "https://rpc.berachain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.berascan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "berachain",
		IsEVM: true,
	},
	4250: {
		ID: 4250, Name: "Metal L2", Symbol: "MTL", Type: "evm",
		RPCEndpoint:    "https://rpc.l2.metal.info",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.l2.metal.info/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "metal",
		IsEVM: true,
	},
	690: {
		ID: 690, Name: "Redstone", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.redstone.xyz",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.redstone.xyz/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	4689: {
		ID: 4689, Name: "IoTeX", Symbol: "IOTX", Type: "evm",
		RPCEndpoint:    "https://babel-api.mainnet.iotex.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://iotexscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "iotex",
		IsEVM: true,
	},
	1030: {
		ID: 1030, Name: "Conflux eSpace", Symbol: "CFX", Type: "evm",
		RPCEndpoint:    "https://evm.confluxrpc.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://evm.confluxscan.net/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "conflux-token",
		IsEVM: true,
	},
	30: {
		ID: 30, Name: "Rootstock", Symbol: "RBTC", Type: "evm",
		RPCEndpoint:    "https://public-node.rsk.co",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://blockscout.com/rsk/mainnet/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "rootstock",
		IsEVM: true,
	},
	1313161554: {
		ID: 1313161554, Name: "Aurora", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://mainnet.aurora.dev",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.aurora.dev/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	8217: {
		ID: 8217, Name: "Klaytn", Symbol: "KLAY", Type: "evm",
		RPCEndpoint:    "https://public-en-cypress.klaytn.net",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://scope.klaytn.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "klay-token",
		IsEVM: true,
	},
	100: {
		ID: 100, Name: "Gnosis", Symbol: "xDAI", Type: "evm",
		RPCEndpoint:    "https://rpc.gnosischain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.gnosisscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "xdai",
		IsEVM: true,
	},
	108: {
		ID: 108, Name: "Telos", Symbol: "TLOS", Type: "evm",
		RPCEndpoint:    "https://mainnet.telos.net/evm",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.teloscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "telos",
		IsEVM: true,
	},
	570: {
		ID: 570, Name: "Rollux", Symbol: "SYS", Type: "evm",
		RPCEndpoint:    "https://rpc.rollux.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.rollux.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "syscoin",
		IsEVM: true,
	},
	1116: {
		ID: 1116, Name: "Core Blockchain", Symbol: "CORE", Type: "evm",
		RPCEndpoint:    "https://rpc.coredao.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://openapi.coredao.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "core",
		IsEVM: true,
	},
	66: {
		ID: 66, Name: "OKX Chain", Symbol: "OKT", Type: "evm",
		RPCEndpoint:    "https://exchainrpc.okex.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://www.oklink.com/api/explorer/oktc", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "okt-chain",
		IsEVM: true,
	},
	82: {
		ID: 82, Name: "Meter", Symbol: "MTR", Type: "evm",
		RPCEndpoint:    "https://rpc.meter.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://scan.meter.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "meter",
		IsEVM: true,
	},
	32520: {
		ID: 32520, Name: "Bitgert", Symbol: "BRIS", Type: "evm",
		RPCEndpoint:    "https://rpc.bitgert.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://brisescan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "bitgert",
		IsEVM: true,
	},
	248: {
		ID: 248, Name: "Oasys", Symbol: "OAS", Type: "evm",
		RPCEndpoint:    "https://rpc.mainnet.oasys.games",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.oasys.games/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "oasys",
		IsEVM: true,
	},
	106: {
		ID: 106, Name: "Velas", Symbol: "VLX", Type: "evm",
		RPCEndpoint:    "https://evmexplorer.velas.com/rpc",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://evmexplorer.velas.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "velas",
		IsEVM: true,
	},
	1088: {
		ID: 1088, Name: "Metis Andromeda", Symbol: "METIS", Type: "evm",
		RPCEndpoint:    "https://andromeda.metis.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://andromeda.explorer.metis.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "metis-token",
		IsEVM: true,
	},
	50: {
		ID: 50, Name: "XDC Network", Symbol: "XDC", Type: "evm",
		RPCEndpoint:    "https://rpc.xdcrpc.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://xdcscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "xdce-cold-chain",
		IsEVM: true,
	},
	10000: {
		ID: 10000, Name: "SmartBCH", Symbol: "BCH", Type: "evm",
		RPCEndpoint:    "https://rpc.smartbch.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://www.smartscan.cash/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "bitcoin-cash",
		IsEVM: true,
	},
	7141: {
		ID: 7141, Name: "Godwoken", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://v1.mainnet.godwoken.io/rpc",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://v1.gwscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	1231: {
		ID: 1231, Name: "Ultron", Symbol: "ULX", Type: "evm",
		RPCEndpoint:    "https://ultron-rpc.net",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.ultron-rpc.net/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ultron",
		IsEVM: true,
	},
	686: {
		ID: 686, Name: "Karak", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.karak.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.karak.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	1515: {
		ID: 1515, Name: "Bifrost", Symbol: "BFC", Type: "evm",
		RPCEndpoint:    "https://public-rpc.bifrostnetwork.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.bifrostnetwork.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "bifrost-native-credit",
		IsEVM: true,
	},
	88: {
		ID: 88, Name: "TomoChain", Symbol: "TOMO", Type: "evm",
		RPCEndpoint:    "https://rpc.tomochain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.tomoscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "tomochain",
		IsEVM: true,
	},
	4893: {
		ID: 4893, Name: "Omni", Symbol: "OMNI", Type: "evm",
		RPCEndpoint:    "https://mainnet.omni.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://omniexplorer.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "omni",
		IsEVM: true,
	},
	2370: {
		ID: 2370, Name: "Fibonacci", Symbol: "FIBO", Type: "evm",
		RPCEndpoint:    "https://fibonacci-rpc.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://fiboscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "fibonacci",
		IsEVM: true,
	},
	998: {
		ID: 998, Name: "Lucky Network", Symbol: "L99", Type: "evm",
		RPCEndpoint:    "https://rpc.luckynetwork.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.luckynetwork.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "lucky-network",
		IsEVM: true,
	},
	499: {
		ID: 499, Name: "Rupaya", Symbol: "RUPX", Type: "evm",
		RPCEndpoint:    "https://rpc.rupaya.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.rupaya.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "rupaya",
		IsEVM: true,
	},
	5551: {
		ID: 5551, Name: "Nahmii", Symbol: "NII", Type: "evm",
		RPCEndpoint:    "https://l2.nahmii.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.nahmii.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "nahmii",
		IsEVM: true,
	},
	1506: {
		ID: 1506, Name: "SherpaX", Symbol: "KSX", Type: "evm",
		RPCEndpoint:    "https://rpc.sherpax.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.sherpax.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "sherpax",
		IsEVM: true,
	},
	8285: {
		ID: 8285, Name: "Kortho", Symbol: "KTO", Type: "evm",
		RPCEndpoint:    "https://rpc.kortho-chain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://korthochain.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "kortho",
		IsEVM: true,
	},
	10058111: {
		ID: 10058111, Name: "Tenet", Symbol: "TENET", Type: "evm",
		RPCEndpoint:    "https://rpc.tenet.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://tenetscan.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "tenet",
		IsEVM: true,
	},
	2330: {
		ID: 2330, Name: "Sommelier", Symbol: "SOMM", Type: "evm",
		RPCEndpoint:    "https://sommelierchain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://sommelierchain.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "sommelier",
		IsEVM: true,
	},
	723: {
		ID: 723, Name: "Lumoz", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.lumoz.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.lumoz.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	122: {
		ID: 122, Name: "Fuse", Symbol: "FUSE", Type: "evm",
		RPCEndpoint:    "https://rpc.fuse.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.fuse.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "fuse-network-token",
		IsEVM: true,
	},
	80: {
		ID: 80, Name: "GeneChain", Symbol: "DNA", Type: "evm",
		RPCEndpoint:    "https://rpc.genechain.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.genechain.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "genechain",
		IsEVM: true,
	},
	787: {
		ID: 787, Name: "Acala EVM", Symbol: "ACA", Type: "evm",
		RPCEndpoint:    "https://eth-rpc-acala.aca-api.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://blockscout.acala.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "acala",
		IsEVM: true,
	},
	128: {
		ID: 128, Name: "HECO", Symbol: "HT", Type: "evm",
		RPCEndpoint:    "https://http-mainnet.hecochain.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.hecoinfo.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "huobi-token",
		IsEVM: true,
	},
	61: {
		ID: 61, Name: "Ethereum Classic", Symbol: "ETC", Type: "evm",
		RPCEndpoint:    "https://etc.rivet.link",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://blockscout.com/etc/mainnet/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum-classic",
		IsEVM: true,
	},
	12052: {
		ID: 12052, Name: "WEMIX3.0", Symbol: "WEMIX", Type: "evm",
		RPCEndpoint:    "https://api.wemix.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.wemix.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "wemix-token",
		IsEVM: true,
	},
	100000: {
		ID: 100000, Name: "Etherlink", Symbol: "XTZ", Type: "evm",
		RPCEndpoint:    "https://node.mainnet.etherlink.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.etherlink.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "tezos",
		IsEVM: true,
	},
	17069: {
		ID: 17069, Name: "Garnet Hubble", Symbol: "ETH", Type: "evm",
		RPCEndpoint:    "https://rpc.garnet.qry.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.garnet.qry.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethereum",
		IsEVM: true,
	},
	60: {
		ID: 60, Name: "GoChain", Symbol: "GO", Type: "evm",
		RPCEndpoint:    "https://rpc.gochain.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.gochain.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "gochain",
		IsEVM: true,
	},
	162: {
		ID: 162, Name: "Lightstreams", Symbol: "PHT", Type: "evm",
		RPCEndpoint:    "https://node.mainnet.lightstreams.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.lightstreams.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "lightstreams",
		IsEVM: true,
	},
	269: {
		ID: 269, Name: "Hpb", Symbol: "HPB", Type: "evm",
		RPCEndpoint:    "https://hpbnode.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://hscan.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "high-performance-blockchain",
		IsEVM: true,
	},
	2612: {
		ID: 2612, Name: "EtherNano", Symbol: "ETHN", Type: "evm",
		RPCEndpoint:    "https://rpc.ethernano.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.ethernano.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ethernano",
		IsEVM: true,
	},
	517: {
		ID: 517, Name: "Gather", Symbol: "GTH", Type: "evm",
		RPCEndpoint:    "https://rpc.gather.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.gather.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "gather",
		IsEVM: true,
	},
	311: {
		ID: 311, Name: "OmniLite", Symbol: "OML", Type: "evm",
		RPCEndpoint:    "https://rpc.omnilite.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.omnilite.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "omnilite",
		IsEVM: true,
	},
	6877: {
		ID: 6877, Name: "UltronGlab", Symbol: "ULG", Type: "evm",
		RPCEndpoint:    "https://rpc.ultronglab.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.ultronglab.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ultronglab",
		IsEVM: true,
	},
	512: {
		ID: 512, Name: "VeloLabs", Symbol: "VELO", Type: "evm",
		RPCEndpoint:    "https://rpc.velolabs.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.velolabs.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "velo",
		IsEVM: true,
	},
	38: {
		ID: 38, Name: "Valorbit", Symbol: "VAL", Type: "evm",
		RPCEndpoint:    "https://rpc.valorbit.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.valorbit.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "valorbit",
		IsEVM: true,
	},
	68: {
		ID: 68, Name: "Soteria", Symbol: "SOTE", Type: "evm",
		RPCEndpoint:    "https://rpc.soteria.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.soteria.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "soteria",
		IsEVM: true,
	},
	65535: {
		ID: 65535, Name: "IPOS Network", Symbol: "IPOS", Type: "evm",
		RPCEndpoint:    "https://rpc.ipos.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.ipos.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ipos-network",
		IsEVM: true,
	},
	2025: {
		ID: 2025, Name: "Sapling", Symbol: "SAPL", Type: "evm",
		RPCEndpoint:    "https://rpc.sapling.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.sapling.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "sapling",
		IsEVM: true,
	},
	11297108114: {
		ID: 11297108114, Name: "Sardis", Symbol: "SARD", Type: "evm",
		RPCEndpoint:    "https://rpc.sardis.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.sardis.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "sardis",
		IsEVM: true,
	},
	555: {
		ID: 555, Name: "VelaChain", Symbol: "VELA", Type: "evm",
		RPCEndpoint:    "https://rpc.velachain.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.velachain.org/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "velachain",
		IsEVM: true,
	},
	11297108112: {
		ID: 11297108112, Name: "Ambros", Symbol: "AMB", Type: "evm",
		RPCEndpoint:    "https://rpc.ambros.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://ambrosscan.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "ambros",
		IsEVM: true,
	},
	1234: {
		ID: 1234, Name: "Step Network", Symbol: "STEP", Type: "evm",
		RPCEndpoint:    "https://rpc.step.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.step.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "step-network",
		IsEVM: true,
	},
	846: {
		ID: 846, Name: "Planq Network", Symbol: "PLQ", Type: "evm",
		RPCEndpoint:    "https://evm-rpc.planq.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://evm.planq.network/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "planq",
		IsEVM: true,
	},
	1000001: {
		ID: 1000001, Name: "Solana", Symbol: "SOL", Type: "solana",
		RPCEndpoint:    "https://api.mainnet-beta.solana.com",
		DerivationPath: "m/44'/501'/0'/0'",
		ExplorerAPI:    "https://api.mainnet-beta.solana.com", ExplorerURL: "",
		Decimals: 9, CoinGeckoID: "solana",
		AddressPrefix: "solana",
		IsEVM:         false,
	},
	1000002: {
		ID: 1000002, Name: "Bitcoin", Symbol: "BTC", Type: "bitcoin",
		RPCEndpoint:    "https://blockstream.info/api",
		DerivationPath: "m/44'/0'/0'/0/0",
		ExplorerAPI:    "https://blockstream.info/api", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "bitcoin",
		AddressPrefix: "bitcoin",
		IsEVM:         false,
	},
	1000003: {
		ID: 1000003, Name: "Tron", Symbol: "TRX", Type: "tron",
		RPCEndpoint:    "https://api.trongrid.io",
		DerivationPath: "m/44'/195'/0'/0/0",
		ExplorerAPI:    "https://apilist.tronscanapi.com/api", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "tron",
		AddressPrefix: "tron",
		IsEVM:         false,
	},
	1000004: {
		ID: 1000004, Name: "Cosmos Hub", Symbol: "ATOM", Type: "cosmos",
		RPCEndpoint:    "https://rpc.cosmos.network",
		DerivationPath: "m/44'/118'/0'/0/0",
		ExplorerAPI:    "https://atomscan.com/api", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "cosmos",
		AddressPrefix: "cosmos",
		IsEVM:         false,
	},
	1000005: {
		ID: 1000005, Name: "Polkadot", Symbol: "DOT", Type: "polkadot",
		RPCEndpoint:    "https://rpc.polkadot.io",
		DerivationPath: "m/44'/354'/0'/0/0",
		ExplorerAPI:    "https://polkadot.js.org/apps", ExplorerURL: "",
		Decimals: 10, CoinGeckoID: "polkadot",
		AddressPrefix: "polkadot",
		IsEVM:         false,
	},
	1000006: {
		ID: 1000006, Name: "Kusama", Symbol: "KSM", Type: "kusama",
		RPCEndpoint:    "https://rpc.kusama.network",
		DerivationPath: "m/44'/434'/0'/0/0",
		ExplorerAPI:    "https://kusama.subscan.io/api", ExplorerURL: "",
		Decimals: 12, CoinGeckoID: "kusama",
		AddressPrefix: "kusama",
		IsEVM:         false,
	},
	1000007: {
		ID: 1000007, Name: "Near", Symbol: "NEAR", Type: "near",
		RPCEndpoint:    "https://rpc.mainnet.near.org",
		DerivationPath: "m/44'/397'/0'/0/0",
		ExplorerAPI:    "https://api.nearblocks.io", ExplorerURL: "",
		Decimals: 24, CoinGeckoID: "near",
		AddressPrefix: "near",
		IsEVM:         false,
	},
	1000008: {
		ID: 1000008, Name: "Aptos", Symbol: "APT", Type: "aptos",
		RPCEndpoint:    "https://fullnode.mainnet.aptoslabs.com",
		DerivationPath: "m/44'/637'/0'/0/0",
		ExplorerAPI:    "https://api.aptoscan.com", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "aptos",
		AddressPrefix: "aptos",
		IsEVM:         false,
	},
	1000009: {
		ID: 1000009, Name: "Sui", Symbol: "SUI", Type: "sui",
		RPCEndpoint:    "https://fullnode.mainnet.sui.io",
		DerivationPath: "m/44'/784'/0'/0/0",
		ExplorerAPI:    "https://suiscan.xyz/api", ExplorerURL: "",
		Decimals: 9, CoinGeckoID: "sui",
		AddressPrefix: "sui",
		IsEVM:         false,
	},
	1000010: {
		ID: 1000010, Name: "Algorand", Symbol: "ALGO", Type: "algorand",
		RPCEndpoint:    "https://mainnet-api.algonode.cloud",
		DerivationPath: "m/44'/283'/0'/0/0",
		ExplorerAPI:    "https://mainnet-idx.algonode.cloud", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "algorand",
		AddressPrefix: "algorand",
		IsEVM:         false,
	},
	1000011: {
		ID: 1000011, Name: "Cardano", Symbol: "ADA", Type: "cardano",
		RPCEndpoint:    "https://cardano-mainnet.blockfrost.io",
		DerivationPath: "m/1852'/1815'/0'/0/0",
		ExplorerAPI:    "https://cardanoscan.io/api", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "cardano",
		AddressPrefix: "cardano",
		IsEVM:         false,
	},
	1000012: {
		ID: 1000012, Name: "Ripple", Symbol: "XRP", Type: "ripple",
		RPCEndpoint:    "https://xrplcluster.com",
		DerivationPath: "m/44'/144'/0'/0/0",
		ExplorerAPI:    "https://data.ripple.com", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "ripple",
		AddressPrefix: "xrp",
		IsEVM:         false,
	},
	1000013: {
		ID: 1000013, Name: "Stellar", Symbol: "XLM", Type: "stellar",
		RPCEndpoint:    "https://horizon.stellar.org",
		DerivationPath: "m/44'/148'/0'/0/0",
		ExplorerAPI:    "https://horizon.stellar.org", ExplorerURL: "",
		Decimals: 7, CoinGeckoID: "stellar",
		AddressPrefix: "stellar",
		IsEVM:         false,
	},
	1000014: {
		ID: 1000014, Name: "Litecoin", Symbol: "LTC", Type: "litecoin",
		RPCEndpoint:    "https://litecoinspace.org/api",
		DerivationPath: "m/44'/2'/0'/0/0",
		ExplorerAPI:    "https://litecoinspace.org/api", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "litecoin",
		AddressPrefix: "litecoin",
		IsEVM:         false,
	},
	1000015: {
		ID: 1000015, Name: "Dogecoin", Symbol: "DOGE", Type: "dogecoin",
		RPCEndpoint:    "https://dogechain.info/api/v1",
		DerivationPath: "m/44'/3'/0'/0/0",
		ExplorerAPI:    "https://dogechain.info/api/v1", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "dogecoin",
		AddressPrefix: "dogecoin",
		IsEVM:         false,
	},
	1000016: {
		ID: 1000016, Name: "Toncoin", Symbol: "TON", Type: "ton",
		RPCEndpoint:    "https://toncenter.com/api/v2",
		DerivationPath: "m/44'/607'/0'/0/0",
		ExplorerAPI:    "https://tonapi.io", ExplorerURL: "",
		Decimals: 9, CoinGeckoID: "the-open-network",
		AddressPrefix: "ton",
		IsEVM:         false,
	},
	1000017: {
		ID: 1000017, Name: "Hedera", Symbol: "HBAR", Type: "hedera",
		RPCEndpoint:    "https://mainnet.mirror.hedera.com",
		DerivationPath: "m/44'/3030'/0'/0/0",
		ExplorerAPI:    "https://hashscan.io/api", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "hedera-hashgraph",
		AddressPrefix: "hedera",
		IsEVM:         false,
	},
	1000018: {
		ID: 1000018, Name: "EOS", Symbol: "EOS", Type: "eos",
		RPCEndpoint:    "https://eos.greymass.com",
		DerivationPath: "m/44'/194'/0'/0/0",
		ExplorerAPI:    "https://api.eossweden.org", ExplorerURL: "",
		Decimals: 4, CoinGeckoID: "eos",
		AddressPrefix: "eos",
		IsEVM:         false,
	},
	1000019: {
		ID: 1000019, Name: "Tezos", Symbol: "XTZ", Type: "tezos",
		RPCEndpoint:    "https://mainnet.api.tzstats.com",
		DerivationPath: "m/44'/1729'/0'/0/0",
		ExplorerAPI:    "https://api.tzstats.com", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "tezos",
		AddressPrefix: "tezos",
		IsEVM:         false,
	},
	1000020: {
		ID: 1000020, Name: "VeChain", Symbol: "VET", Type: "vechain",
		RPCEndpoint:    "https://sync-mainnet.vechain.org",
		DerivationPath: "m/44'/818'/0'/0/0",
		ExplorerAPI:    "https://vechainstats.com/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "vechain",
		AddressPrefix: "vechain",
		IsEVM:         false,
	},
	1000021: {
		ID: 1000021, Name: "WAX", Symbol: "WAX", Type: "wax",
		RPCEndpoint:    "https://wax.greymass.com",
		DerivationPath: "m/44'/14000'/0'/0/0",
		ExplorerAPI:    "https://api.waxsweden.org", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "wax",
		AddressPrefix: "wax",
		IsEVM:         false,
	},
	1000022: {
		ID: 1000022, Name: "Monero", Symbol: "XMR", Type: "monero",
		RPCEndpoint:    "https://node.community.rino.io",
		DerivationPath: "m/44'/128'/0'/0/0",
		ExplorerAPI:    "https://xmrchain.net/api", ExplorerURL: "",
		Decimals: 12, CoinGeckoID: "monero",
		AddressPrefix: "monero",
		IsEVM:         false,
	},
	1000023: {
		ID: 1000023, Name: "Zcash", Symbol: "ZEC", Type: "zcash",
		RPCEndpoint:    "https://mainnet.lightwalletd.com",
		DerivationPath: "m/44'/133'/0'/0/0",
		ExplorerAPI:    "https://blockbook.zecwallet.co", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "zcash",
		AddressPrefix: "zcash",
		IsEVM:         false,
	},
	1000024: {
		ID: 1000024, Name: "Dash", Symbol: "DASH", Type: "dash",
		RPCEndpoint:    "https://insight.dash.org",
		DerivationPath: "m/44'/5'/0'/0/0",
		ExplorerAPI:    "https://insight.dash.org/api", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "dash",
		AddressPrefix: "dash",
		IsEVM:         false,
	},
	1000025: {
		ID: 1000025, Name: "Zilliqa", Symbol: "ZIL", Type: "zilliqa",
		RPCEndpoint:    "https://api.zilliqa.com",
		DerivationPath: "m/44'/313'/0'/0/0",
		ExplorerAPI:    "https://api.zilliqa.com", ExplorerURL: "",
		Decimals: 12, CoinGeckoID: "zilliqa",
		AddressPrefix: "zilliqa",
		IsEVM:         false,
	},
	1000026: {
		ID: 1000026, Name: "Ergo", Symbol: "ERG", Type: "ergo",
		RPCEndpoint:    "https://node.ergo.ovh",
		DerivationPath: "m/44'/429'/0'/0/0",
		ExplorerAPI:    "https://api.ergoplatform.com", ExplorerURL: "",
		Decimals: 9, CoinGeckoID: "ergo",
		AddressPrefix: "ergo",
		IsEVM:         false,
	},
	1000027: {
		ID: 1000027, Name: "Nervos CKB", Symbol: "CKB", Type: "nervos",
		RPCEndpoint:    "https://mainnet.ckb.dev/rpc",
		DerivationPath: "m/44'/309'/0'/0/0",
		ExplorerAPI:    "https://api.ckbexplorer.com", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "nervos-network",
		AddressPrefix: "nervos",
		IsEVM:         false,
	},
	1000028: {
		ID: 1000028, Name: "Aion", Symbol: "AION", Type: "aion",
		RPCEndpoint:    "https://aion.api.coinc.org",
		DerivationPath: "m/44'/425'/0'/0/0",
		ExplorerAPI:    "https://mainnet.aion.network", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "aion",
		AddressPrefix: "aion",
		IsEVM:         false,
	},
	1000029: {
		ID: 1000029, Name: "Waves", Symbol: "WAVES", Type: "waves",
		RPCEndpoint:    "https://nodes.wavesnodes.com",
		DerivationPath: "m/44'/5741562'/0'/0/0",
		ExplorerAPI:    "https://nodes.wavesnodes.com", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "waves",
		AddressPrefix: "waves",
		IsEVM:         false,
	},
	1000030: {
		ID: 1000030, Name: "Chainflip", Symbol: "FLIP", Type: "chainflip",
		RPCEndpoint:    "https://chainflip.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://scan.chainflip.io/api", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "chainflip",
		AddressPrefix: "chainflip",
		IsEVM:         false,
	},
	1000031: {
		ID: 1000031, Name: "Sei", Symbol: "SEI", Type: "sei",
		RPCEndpoint:    "https://rpc.sei-apis.com",
		DerivationPath: "m/44'/1022'/0'/0/0",
		ExplorerAPI:    "https://api.seiscan.io", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "sei-network",
		AddressPrefix: "sei",
		IsEVM:         false,
	},
	1000032: {
		ID: 1000032, Name: "Celestia", Symbol: "TIA", Type: "celestia",
		RPCEndpoint:    "https://rpc.lava.ws",
		DerivationPath: "m/44'/118'/0'/0/0",
		ExplorerAPI:    "https://celestia.explorer.nodes.guru/api", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "celestoken",
		AddressPrefix: "celestia",
		IsEVM:         false,
	},
	1000033: {
		ID: 1000033, Name: "Starknet", Symbol: "STRK", Type: "starknet",
		RPCEndpoint:    "https://rpc.starknet.io",
		DerivationPath: "m/44'/9004'/0'/0/0",
		ExplorerAPI:    "https://api.starkscan.io", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "starknet",
		AddressPrefix: "starknet",
		IsEVM:         false,
	},
	1000034: {
		ID: 1000034, Name: "Injective", Symbol: "INJ", Type: "injective",
		RPCEndpoint:    "https://injective-rpc.publicnode.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://api.explorer.injective.network", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "injective-protocol",
		AddressPrefix: "injective",
		IsEVM:         false,
	},
	1000035: {
		ID: 1000035, Name: "Osmosis", Symbol: "OSMO", Type: "osmosis",
		RPCEndpoint:    "https://rpc.osmosis.zone",
		DerivationPath: "m/44'/118'/0'/0/0",
		ExplorerAPI:    "https://api.mintscan.io", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "osmosis",
		AddressPrefix: "osmosis",
		IsEVM:         false,
	},
	1000036: {
		ID: 1000036, Name: "Dymension", Symbol: "DYM", Type: "dymension",
		RPCEndpoint:    "https://dymension-rpc.lava.ws",
		DerivationPath: "m/44'/118'/0'/0/0",
		ExplorerAPI:    "https://api.mintscan.io", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "dymension",
		AddressPrefix: "dymension",
		IsEVM:         false,
	},
	1000037: {
		ID: 1000037, Name: "MultiversX", Symbol: "EGLD", Type: "multiversx",
		RPCEndpoint:    "https://api.multiversx.com",
		DerivationPath: "m/44'/508'/0'/0/0",
		ExplorerAPI:    "https://api.multiversx.com", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "elrond-erd-2",
		AddressPrefix: "multiversx",
		IsEVM:         false,
	},
	1000038: {
		ID: 1000038, Name: "Casper", Symbol: "CSPR", Type: "casper",
		RPCEndpoint:    "https://node.casper.network",
		DerivationPath: "m/44'/506'/0'/0/0",
		ExplorerAPI:    "https://api.cspr.live", ExplorerURL: "",
		Decimals: 9, CoinGeckoID: "casper-network",
		AddressPrefix: "casper",
		IsEVM:         false,
	},
	1000039: {
		ID: 1000039, Name: "Flow", Symbol: "FLOW", Type: "flow",
		RPCEndpoint:    "https://rest-mainnet.onflow.org",
		DerivationPath: "m/44'/539'/0'/0/0",
		ExplorerAPI:    "https://api.flowscan.io", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "flow",
		AddressPrefix: "flow",
		IsEVM:         false,
	},
	1000040: {
		ID: 1000040, Name: "Radix", Symbol: "XRD", Type: "radix",
		RPCEndpoint:    "https://mainnet.radixdlt.com",
		DerivationPath: "m/44'/1022'/0'/0/0",
		ExplorerAPI:    "https://dashboard.radixdlt.com", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "radix",
		AddressPrefix: "radix",
		IsEVM:         false,
	},
	1000041: {
		ID: 1000041, Name: "Kadena", Symbol: "KDA", Type: "kadena",
		RPCEndpoint:    "https://api.chainweb.com",
		DerivationPath: "m/44'/626'/0'/0/0",
		ExplorerAPI:    "https://explorer.chainweb.com", ExplorerURL: "",
		Decimals: 12, CoinGeckoID: "kadena",
		AddressPrefix: "kadena",
		IsEVM:         false,
	},
	1000042: {
		ID: 1000042, Name: "Pi Network", Symbol: "PI", Type: "pi",
		RPCEndpoint:    "https://api.pinetwork.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://explorer.pinetwork.org", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "pi-network",
		AddressPrefix: "pi",
		IsEVM:         false,
	},
	1000043: {
		ID: 1000043, Name: "Aleo", Symbol: "ALEO", Type: "aleo",
		RPCEndpoint:    "https://api.aleo.org",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://aleo.network", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "aleo",
		AddressPrefix: "aleo",
		IsEVM:         false,
	},
	1000044: {
		ID: 1000044, Name: "Fuel", Symbol: "FUEL", Type: "fuel",
		RPCEndpoint:    "https://fuel-network.io",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://fuelscan.io", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "fuel",
		AddressPrefix: "fuel",
		IsEVM:         false,
	},
	1000045: {
		ID: 1000045, Name: "Risc Zero", Symbol: "RISC", Type: "risczero",
		RPCEndpoint:    "https://risczero.com",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://scan.risczero.com", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "risczero",
		AddressPrefix: "risczero",
		IsEVM:         false,
	},
	1000046: {
		ID: 1000046, Name: "Aztec", Symbol: "AZT", Type: "aztec",
		RPCEndpoint:    "https://aztec.network",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://aztecscan.com", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "aztec",
		AddressPrefix: "aztec",
		IsEVM:         false,
	},
	1000047: {
		ID: 1000047, Name: "Nil Foundation", Symbol: "NIL", Type: "nil",
		RPCEndpoint:    "https://nil.foundation",
		DerivationPath: "m/44'/60'/0'/0/0",
		ExplorerAPI:    "https://nilscan.io", ExplorerURL: "",
		Decimals: 18, CoinGeckoID: "nil-foundation",
		AddressPrefix: "nil",
		IsEVM:         false,
	},
	1000048: {
		ID: 1000048, Name: "Bitcoin Cash", Symbol: "BCH", Type: "bitcoincash",
		RPCEndpoint:    "https://api.fullstack.cash",
		DerivationPath: "m/44'/145'/0'/0/0",
		ExplorerAPI:    "https://blockchair.com/bitcoin-cash", ExplorerURL: "",
		Decimals: 8, CoinGeckoID: "bitcoin-cash",
		AddressPrefix: "bitcoincash",
		IsEVM:         false,
	},
	1000049: {
		ID: 1000049, Name: "Juno", Symbol: "JUNO", Type: "juno",
		RPCEndpoint:    "https://rpc.juno.strange.love",
		DerivationPath: "m/44'/118'/0'/0/0",
		ExplorerAPI:    "https://api.mintscan.io", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "juno-network",
		AddressPrefix: "juno",
		IsEVM:         false,
	},
	1000050: {
		ID: 1000050, Name: "Stargaze", Symbol: "STARS", Type: "stargaze",
		RPCEndpoint:    "https://rpc.stargaze-apis.com",
		DerivationPath: "m/44'/118'/0'/0/0",
		ExplorerAPI:    "https://api.mintscan.io", ExplorerURL: "",
		Decimals: 6, CoinGeckoID: "stargaze",
		AddressPrefix: "stargaze",
		IsEVM:         false,
	},
}

// chainByID returns a chain config or nil. Supports both EVM (by real
// chain ID) and non-EVM (by synthetic registry ID) lookups.
func chainByID(id int64) *ChainConfig {
	if c, ok := SupportedChains[id]; ok {
		// allow env override of RPC + explorer
		if v := envOr(fmt.Sprintf("CHAIN_%d_RPC", id), ""); v != "" {
			c.RPCEndpoint = v
		}
		if v := envOr(fmt.Sprintf("CHAIN_%d_EXPLORER", id), ""); v != "" {
			c.ExplorerAPI = v
		}
		return &c
	}
	return nil
}

// evmChainByChainID returns an EVM chain config by its real EVM chain ID,
// or nil if the chain is not EVM-supported. Used by EVM-only operations
// (balance, signing, broadcast) which must not run against non-EVM chains.
func evmChainByChainID(id int64) *ChainConfig {
	c := chainByID(id)
	if c == nil || !c.IsEVM {
		return nil
	}
	return c
}
