package main

// Code generated by /tmp/gen_go.py from curated public mainnet RPC
// documentation for non-EVM chains. DO NOT EDIT by hand. Each entry uses a
// REAL publicly documented mainnet endpoint; none are testnets/stubs.
// Pi Network is included with an empty rpc_endpoint because its enclosed
// mainnet does not publish a public community JSON-RPC — the operator must
// configure the node RPC via CHAIN_<ID>_RPC or the admin_chain_config table,
// and the runtime honestly reports the chain as RPC-unconfigured otherwise.

var nonEVMMainnet = []ChainConfig{
	{
		ID: 9000000000, Name: "Bitcoin", Symbol: "BTC", RPCEndpoint: "https://blockstream.info/api", DerivationPath: "m/44'/0'/0'/0/0", ExplorerAPI: "https://mempool.space", ExplorerURL: "https://mempool.space", ChainType: "bitcoin", Decimals: 8, CoinType: 0, IsTestnet: false,
	},
	{
		ID: 9000000002, Name: "Litecoin", Symbol: "LTC", RPCEndpoint: "https://litecoinspace.org/api", DerivationPath: "m/44'/2'/0'/0/0", ExplorerAPI: "https://blockchair.com/litecoin", ExplorerURL: "https://blockchair.com/litecoin", ChainType: "litecoin", Decimals: 8, CoinType: 2, IsTestnet: false,
	},
	{
		ID: 9000000003, Name: "Dogecoin", Symbol: "DOGE", RPCEndpoint: "https://dogechain.info/api/v1", DerivationPath: "m/44'/3'/0'/0/0", ExplorerAPI: "https://blockchair.com/dogecoin", ExplorerURL: "https://blockchair.com/dogecoin", ChainType: "dogecoin", Decimals: 8, CoinType: 3, IsTestnet: false,
	},
	{
		ID: 9000000005, Name: "Dash", Symbol: "DASH", RPCEndpoint: "https://insight.dash.org/insight-api", DerivationPath: "m/44'/5'/0'/0/0", ExplorerAPI: "https://blockchair.com/dash", ExplorerURL: "https://blockchair.com/dash", ChainType: "dash", Decimals: 8, CoinType: 5, IsTestnet: false,
	},
	{
		ID: 9000000145, Name: "Bitcoin Cash", Symbol: "BCH", RPCEndpoint: "https://api.blockchair.com/bitcoin-cash", DerivationPath: "m/44'/145'/0'/0/0", ExplorerAPI: "https://blockchair.com/bitcoin-cash", ExplorerURL: "https://blockchair.com/bitcoin-cash", ChainType: "bitcoincash", Decimals: 8, CoinType: 145, IsTestnet: false,
	},
	{
		ID: 9000000236, Name: "Bitcoin SV", Symbol: "BSV", RPCEndpoint: "https://api.blockchair.com/bitcoin-sv", DerivationPath: "m/44'/236'/0'/0/0", ExplorerAPI: "https://blockchair.com/bitcoin-sv", ExplorerURL: "https://blockchair.com/bitcoin-sv", ChainType: "bitcoinsv", Decimals: 8, CoinType: 236, IsTestnet: false,
	},
	{
		ID: 9000000899, Name: "eCash", Symbol: "XEC", RPCEndpoint: "https://explorer.e.cash/api", DerivationPath: "m/44'/899'/0'/0/0", ExplorerAPI: "https://explorer.e.cash", ExplorerURL: "https://explorer.e.cash", ChainType: "ecash", Decimals: 2, CoinType: 899, IsTestnet: false,
	},
	{
		ID: 9000000175, Name: "Ravencoin", Symbol: "RVN", RPCEndpoint: "https://ravencoin.network/api", DerivationPath: "m/44'/175'/0'/0/0", ExplorerAPI: "https://ravencoin.network", ExplorerURL: "https://ravencoin.network", ChainType: "raven", Decimals: 8, CoinType: 175, IsTestnet: false,
	},
	{
		ID: 9000000133, Name: "Zcash", Symbol: "ZEC", RPCEndpoint: "https://lwdv3.zecwallet.co", DerivationPath: "m/44'/133'/0'/0/0", ExplorerAPI: "https://blockchair.com/zcash", ExplorerURL: "https://blockchair.com/zcash", ChainType: "zcash", Decimals: 8, CoinType: 133, IsTestnet: false,
	},
	{
		ID: 9000000017, Name: "Groestlcoin", Symbol: "GRS", RPCEndpoint: "https://groestlsight.groestlcoin.org/api", DerivationPath: "m/44'/17'/0'/0/0", ExplorerAPI: "https://groestlsight.groestlcoin.org", ExplorerURL: "https://groestlsight.groestlcoin.org", ChainType: "groestlcoin", Decimals: 8, CoinType: 17, IsTestnet: false,
	},
	{
		ID: 9000000020, Name: "DigiByte", Symbol: "DGB", RPCEndpoint: "https://digiexplorer.info/api/v2", DerivationPath: "m/44'/20'/0'/0/0", ExplorerAPI: "https://digiexplorer.info", ExplorerURL: "https://digiexplorer.info", ChainType: "digibyte", Decimals: 8, CoinType: 20, IsTestnet: false,
	},
	{
		ID: 9000002301, Name: "Qtum", Symbol: "QTUM", RPCEndpoint: "https://qtum.info/api", DerivationPath: "m/44'/2301'/0'/0/0", ExplorerAPI: "https://qtum.info", ExplorerURL: "https://qtum.info", ChainType: "qtum", Decimals: 8, CoinType: 2301, IsTestnet: false,
	},
	{
		ID: 9000000077, Name: "Verge", Symbol: "XVG", RPCEndpoint: "https://api.vergecurrency.network", DerivationPath: "m/44'/77'/0'/0/0", ExplorerAPI: "https://verge-blockchain.info", ExplorerURL: "https://verge-blockchain.info", ChainType: "verge", Decimals: 6, CoinType: 77, IsTestnet: false,
	},
	{
		ID: 9000000007, Name: "Namecoin", Symbol: "NMC", RPCEndpoint: "https://namecoin.info/api", DerivationPath: "m/44'/7'/0'/0/0", ExplorerAPI: "https://namecoin.info", ExplorerURL: "https://namecoin.info", ChainType: "namecoin", Decimals: 8, CoinType: 7, IsTestnet: false,
	},
	{
		ID: 9000000022, Name: "Monacoin", Symbol: "MONA", RPCEndpoint: "https://mona.chainsight.info/api", DerivationPath: "m/44'/22'/0'/0/0", ExplorerAPI: "https://mona.chainsight.info", ExplorerURL: "https://mona.chainsight.info", ChainType: "monacoin", Decimals: 8, CoinType: 22, IsTestnet: false,
	},
	{
		ID: 9000000010, Name: "BlackCoin", Symbol: "BLK", RPCEndpoint: "https://cryptoid.info/blk/api", DerivationPath: "m/44'/10'/0'/0/0", ExplorerAPI: "https://chainz.cryptoid.org/blk", ExplorerURL: "https://chainz.cryptoid.org/blk", ChainType: "blackcoin", Decimals: 8, CoinType: 10, IsTestnet: false,
	},
	{
		ID: 9000000141, Name: "Komodo", Symbol: "KMD", RPCEndpoint: "https://kmdexplorer.io/api", DerivationPath: "m/44'/141'/0'/0/0", ExplorerAPI: "https://kmdexplorer.io", ExplorerURL: "https://kmdexplorer.io", ChainType: "komodo", Decimals: 8, CoinType: 141, IsTestnet: false,
	},
	{
		ID: 9000000501, Name: "Solana", Symbol: "SOL", RPCEndpoint: "https://api.mainnet-beta.solana.com", DerivationPath: "m/44'/501'/0'/0/0", ExplorerAPI: "https://solscan.io", ExplorerURL: "https://solscan.io", ChainType: "solana", Decimals: 9, CoinType: 501, IsTestnet: false,
	},
	{
		ID: 9000000637, Name: "Aptos", Symbol: "APT", RPCEndpoint: "https://fullnode.mainnet.aptoslabs.com", DerivationPath: "m/44'/637'/0'/0/0", ExplorerAPI: "https://aptoscan.com", ExplorerURL: "https://aptoscan.com", ChainType: "aptos", Decimals: 8, CoinType: 637, IsTestnet: false,
	},
	{
		ID: 9000000784, Name: "Sui", Symbol: "SUI", RPCEndpoint: "https://fullnode.mainnet.sui.io", DerivationPath: "m/44'/784'/0'/0/0", ExplorerAPI: "https://suiscan.xyz", ExplorerURL: "https://suiscan.xyz", ChainType: "sui", Decimals: 9, CoinType: 784, IsTestnet: false,
	},
	{
		ID: 9000000607, Name: "TON", Symbol: "TON", RPCEndpoint: "https://toncenter.com/api/v2/jsonRPC", DerivationPath: "m/44'/607'/0'/0/0", ExplorerAPI: "https://tonscan.org", ExplorerURL: "https://tonscan.org", ChainType: "ton", Decimals: 9, CoinType: 607, IsTestnet: false,
	},
	{
		ID: 9000000118, Name: "Cosmos Hub", Symbol: "ATOM", RPCEndpoint: "https://rpc.cosmos.directory/cosmoshub", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/cosmos", ExplorerURL: "https://www.mintscan.io/cosmos", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000000529, Name: "Secret Network", Symbol: "SCRT", RPCEndpoint: "https://rpc.cosmos.directory/secret", DerivationPath: "m/44'/529'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/secret", ExplorerURL: "https://www.mintscan.io/secret", ChainType: "cosmos", Decimals: 6, CoinType: 529, IsTestnet: false,
	},
	{
		ID: 9000000330, Name: "Terra Classic", Symbol: "LUNC", RPCEndpoint: "https://terra-classic-rpc.publicnode.com", DerivationPath: "m/44'/330'/0'/0/0", ExplorerAPI: "https://finder.terra.money/classic", ExplorerURL: "https://finder.terra.money/classic", ChainType: "cosmos", Decimals: 6, CoinType: 330, IsTestnet: false,
	},
	{
		ID: 9000073068, Name: "Injective", Symbol: "INJ", RPCEndpoint: "https://injective-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/injective", ExplorerURL: "https://www.mintscan.io/injective", ChainType: "cosmos", Decimals: 18, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000014648, Name: "Celestia", Symbol: "TIA", RPCEndpoint: "https://celestia-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/celestia", ExplorerURL: "https://www.mintscan.io/celestia", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000026317, Name: "Osmosis", Symbol: "OSMO", RPCEndpoint: "https://osmosis-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/osmosis", ExplorerURL: "https://www.mintscan.io/osmosis", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000049823, Name: "dYdX", Symbol: "DYDX", RPCEndpoint: "https://dydx-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/dydx", ExplorerURL: "https://www.mintscan.io/dydx", ChainType: "cosmos", Decimals: 18, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000073741, Name: "Sei", Symbol: "SEI", RPCEndpoint: "https://sei-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/sei", ExplorerURL: "https://www.mintscan.io/sei", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000041857, Name: "Kujira", Symbol: "KUJI", RPCEndpoint: "https://kujira-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/kujira", ExplorerURL: "https://www.mintscan.io/kujira", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000012099, Name: "Stride", Symbol: "STRD", RPCEndpoint: "https://stride-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/stride", ExplorerURL: "https://www.mintscan.io/stride", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000090063, Name: "Neutron", Symbol: "NTRN", RPCEndpoint: "https://neutron-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/neutron", ExplorerURL: "https://www.mintscan.io/neutron", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000005267, Name: "Juno", Symbol: "JUNO", RPCEndpoint: "https://juno-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/juno", ExplorerURL: "https://www.mintscan.io/juno", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000007183, Name: "Akash", Symbol: "AKT", RPCEndpoint: "https://akash-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/akash", ExplorerURL: "https://www.mintscan.io/akash", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000018759, Name: "Persistence", Symbol: "XPRT", RPCEndpoint: "https://persistence-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/persistence", ExplorerURL: "https://www.mintscan.io/persistence", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000034677, Name: "Evmos (cosmos)", Symbol: "EVMOS", RPCEndpoint: "https://evmos-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/evmos", ExplorerURL: "https://www.mintscan.io/evmos", ChainType: "cosmos", Decimals: 18, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000054841, Name: "Canto (cosmos)", Symbol: "CANTO", RPCEndpoint: "https://canto-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/canto", ExplorerURL: "https://www.mintscan.io/canto", ChainType: "cosmos", Decimals: 18, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000003318, Name: "Kava (cosmos)", Symbol: "KAVA", RPCEndpoint: "https://kava-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/kava", ExplorerURL: "https://www.mintscan.io/kava", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000062954, Name: "Cronos (cosmos)", Symbol: "CRO", RPCEndpoint: "https://cronos-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/cronos", ExplorerURL: "https://www.mintscan.io/cronos", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000016892, Name: "Stargaze", Symbol: "STARS", RPCEndpoint: "https://stargaze-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/stargaze", ExplorerURL: "https://www.mintscan.io/stargaze", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000021252, Name: "Saga", Symbol: "SAGA", RPCEndpoint: "https://saga-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/saga", ExplorerURL: "https://www.mintscan.io/saga", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000086660, Name: "Noble", Symbol: "USDC", RPCEndpoint: "https://noble-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/noble", ExplorerURL: "https://www.mintscan.io/noble", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000040572, Name: "Axelar", Symbol: "AXL", RPCEndpoint: "https://axelar-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/axelar", ExplorerURL: "https://www.mintscan.io/axelar", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000007153, Name: "UMEE", Symbol: "UMEE", RPCEndpoint: "https://umee-rpc.publicnode.com", DerivationPath: "m/44'/118'/0'/0/0", ExplorerAPI: "https://www.mintscan.io/umee", ExplorerURL: "https://www.mintscan.io/umee", ChainType: "cosmos", Decimals: 6, CoinType: 118, IsTestnet: false,
	},
	{
		ID: 9000000354, Name: "Polkadot", Symbol: "DOT", RPCEndpoint: "https://rpc.polkadot.io", DerivationPath: "m/44'/354'/0'/0/0", ExplorerAPI: "https://polkadot.subscan.io", ExplorerURL: "https://polkadot.subscan.io", ChainType: "polkadot", Decimals: 10, CoinType: 354, IsTestnet: false,
	},
	{
		ID: 9000000434, Name: "Kusama", Symbol: "KSM", RPCEndpoint: "https://kusama-rpc.polkadot.io", DerivationPath: "m/44'/434'/0'/0/0", ExplorerAPI: "https://kusama.subscan.io", ExplorerURL: "https://kusama.subscan.io", ChainType: "polkadot", Decimals: 12, CoinType: 434, IsTestnet: false,
	},
	{
		ID: 9000000397, Name: "NEAR", Symbol: "NEAR", RPCEndpoint: "https://rpc.mainnet.near.org", DerivationPath: "m/44'/397'/0'/0/0", ExplorerAPI: "https://nearblocks.io", ExplorerURL: "https://nearblocks.io", ChainType: "near", Decimals: 24, CoinType: 397, IsTestnet: false,
	},
	{
		ID: 9000000283, Name: "Algorand", Symbol: "ALGO", RPCEndpoint: "https://mainnet-api.algonode.cloud", DerivationPath: "m/44'/283'/0'/0/0", ExplorerAPI: "https://lora.algokit.io/mainnet", ExplorerURL: "https://lora.algokit.io/mainnet", ChainType: "algorand", Decimals: 6, CoinType: 283, IsTestnet: false,
	},
	{
		ID: 9000001815, Name: "Cardano", Symbol: "ADA", RPCEndpoint: "https://cardano-mainnet.blockfrost.io/api/v0", DerivationPath: "m/1852'/1815'/0'/0/0", ExplorerAPI: "https://cardanoscan.io", ExplorerURL: "https://cardanoscan.io", ChainType: "cardano", Decimals: 6, CoinType: 1815, IsTestnet: false,
	},
	{
		ID: 9000000144, Name: "XRP Ledger", Symbol: "XRP", RPCEndpoint: "https://xrplcluster.com", DerivationPath: "m/44'/144'/0'/0/0", ExplorerAPI: "https://livenet.xrpl.org", ExplorerURL: "https://livenet.xrpl.org", ChainType: "ripple", Decimals: 6, CoinType: 144, IsTestnet: false,
	},
	{
		ID: 9000000148, Name: "Stellar", Symbol: "XLM", RPCEndpoint: "https://horizon.stellar.org", DerivationPath: "m/44'/148'/0'/0/0", ExplorerAPI: "https://stellar.expert/explorer/public", ExplorerURL: "https://stellar.expert/explorer/public", ChainType: "stellar", Decimals: 7, CoinType: 148, IsTestnet: false,
	},
	{
		ID: 9000003030, Name: "Hedera", Symbol: "HBAR", RPCEndpoint: "https://mainnet.mirrornode.hedera.com", DerivationPath: "m/44'/3030'/0'/0/0", ExplorerAPI: "https://hashscan.io/mainnet", ExplorerURL: "https://hashscan.io/mainnet", ChainType: "hedera", Decimals: 8, CoinType: 3030, IsTestnet: false,
	},
	{
		ID: 9000001729, Name: "Tezos", Symbol: "XTZ", RPCEndpoint: "https://mainnet.api.tez.ie", DerivationPath: "m/44'/1729'/0'/0/0", ExplorerAPI: "https://tzkt.io", ExplorerURL: "https://tzkt.io", ChainType: "tezos", Decimals: 6, CoinType: 1729, IsTestnet: false,
	},
	{
		ID: 9000000539, Name: "Flow", Symbol: "FLOW", RPCEndpoint: "https://rest-mainnet.onflow.org", DerivationPath: "m/44'/539'/0'/0/0", ExplorerAPI: "https://flowscan.org", ExplorerURL: "https://flowscan.org", ChainType: "flow", Decimals: 8, CoinType: 539, IsTestnet: false,
	},
	{
		ID: 9000111111, Name: "Kaspa", Symbol: "KAS", RPCEndpoint: "https://api.kaspa.org", DerivationPath: "m/44'/111111'/0'/0/0", ExplorerAPI: "https://kaspa.fyi", ExplorerURL: "https://kaspa.fyi", ChainType: "kaspa", Decimals: 2, CoinType: 111111, IsTestnet: false,
	},
	{
		ID: 9000000165, Name: "Nano", Symbol: "XNO", RPCEndpoint: "https://node.somenano.com/api", DerivationPath: "m/44'/165'/0'/0/0", ExplorerAPI: "https://nanolooker.com", ExplorerURL: "https://nanolooker.com", ChainType: "nano", Decimals: 30, CoinType: 165, IsTestnet: false,
	},
	{
		ID: 9000000195, Name: "Tron", Symbol: "TRX", RPCEndpoint: "https://api.trongrid.io", DerivationPath: "m/44'/195'/0'/0/0", ExplorerAPI: "https://tronscan.org", ExplorerURL: "https://tronscan.org", ChainType: "tron", Decimals: 6, CoinType: 195, IsTestnet: false,
	},
	{
		ID: 9000000818, Name: "VeChain", Symbol: "VET", RPCEndpoint: "https://mainnet.vechain.org", DerivationPath: "m/44'/818'/0'/0/0", ExplorerAPI: "https://explore.vechain.org", ExplorerURL: "https://explore.vechain.org", ChainType: "vechain", Decimals: 18, CoinType: 818, IsTestnet: false,
	},
	{
		ID: 9005741564, Name: "Waves", Symbol: "WAVES", RPCEndpoint: "https://nodes.wavesnodes.com", DerivationPath: "m/44'/5741564'/0'/0/0", ExplorerAPI: "https://wavesexplorer.com", ExplorerURL: "https://wavesexplorer.com", ChainType: "waves", Decimals: 8, CoinType: 5741564, IsTestnet: false,
	},
	{
		ID: 9000000508, Name: "Elrond", Symbol: "EGLD", RPCEndpoint: "https://api.elrond.com", DerivationPath: "m/44'/508'/0'/0/0", ExplorerAPI: "https://explorer.multiversx.com", ExplorerURL: "https://explorer.multiversx.com", ChainType: "elrond", Decimals: 18, CoinType: 508, IsTestnet: false,
	},
	{
		ID: 9000000313, Name: "Zilliqa", Symbol: "ZIL", RPCEndpoint: "https://api.zilliqa.com", DerivationPath: "m/44'/313'/0'/0/0", ExplorerAPI: "https://devex.zilliqa.com", ExplorerURL: "https://devex.zilliqa.com", ChainType: "zilliqa", Decimals: 12, CoinType: 313, IsTestnet: false,
	},
	{
		ID: 9000000461, Name: "Filecoin", Symbol: "FIL", RPCEndpoint: "https://api.node.glif.io/rpc/v0", DerivationPath: "m/44'/461'/0'/0/0", ExplorerAPI: "https://filfox.info/en", ExplorerURL: "https://filfox.info/en", ChainType: "filecoin", Decimals: 18, CoinType: 461, IsTestnet: false,
	},
	{
		ID: 9000000223, Name: "Internet Computer", Symbol: "ICP", RPCEndpoint: "https://ic0.app/api", DerivationPath: "m/44'/223'/0'/0/0", ExplorerAPI: "https://dashboard.internetcomputer.org", ExplorerURL: "https://dashboard.internetcomputer.org", ChainType: "internetcomputer", Decimals: 8, CoinType: 223, IsTestnet: false,
	},
	{
		ID: 9000042554, Name: "Aleo", Symbol: "ALEO", RPCEndpoint: "https://api.aleo.network", DerivationPath: "m/44'/42554'/0'/0/0", ExplorerAPI: "https://explorer.aleo.org", ExplorerURL: "https://explorer.aleo.org", ChainType: "aleo", Decimals: 6, CoinType: 42554, IsTestnet: false,
	},
	{
		ID: 9000000309, Name: "Nervos CKB", Symbol: "CKB", RPCEndpoint: "https://mainnet.ckb.dev/rpc", DerivationPath: "m/44'/309'/0'/0/0", ExplorerAPI: "https://explorer.nervos.org", ExplorerURL: "https://explorer.nervos.org", ChainType: "nervos", Decimals: 8, CoinType: 309, IsTestnet: false,
	},
	{
		ID: 9000004242, Name: "Pi Network", Symbol: "PI", RPCEndpoint: "", DerivationPath: "m/44'/4242'/0'/0/0", ExplorerAPI: "https://blockexplorer.minepi.com", ExplorerURL: "https://blockexplorer.minepi.com", ChainType: "pi", Decimals: 8, CoinType: 4242, IsTestnet: false,
	},
}

const nonEVMMainnetCount = 66
