// TigerWallet App Constants
// All configuration values for the application

class AppConstants {
  // App Info
  static const String appName = 'TigerWallet';
  static const String appVersion = '1.0.0';
  static const String appBuildNumber = '1';
  
  // API Endpoints — canonical Go wallet-api backend (go/wallet_api, port 8443).
  // Override at build time with --dart-define=API_BASE_URL=... for production.
  static const String baseUrl =
      String.fromEnvironment('API_BASE_URL', defaultValue: 'http://localhost:8443');
  static const String p2pServiceUrl =
      String.fromEnvironment('P2P_SERVICE_URL', defaultValue: 'http://localhost:8007');
  static const String wsUrl =
      String.fromEnvironment('API_WS_URL', defaultValue: 'ws://localhost:8443/ws');
  
  // Blockchain RPC URLs (100+ chains)
  static const Map<String, String> rpcEndpoints = {
    // EVM Chains
    'ethereum': 'https://eth.llamarpc.com',
    'sepolia': 'https://rpc.sepolia.org',
    'bsc': 'https://bsc-dataseed.binance.org',
    'polygon': 'https://polygon-rpc.com',
    'arbitrum': 'https://arb1.arbitrum.io/rpc',
    'optimism': 'https://mainnet.optimism.io',
    'base': 'https://mainnet.base.org',
    'avalanche': 'https://api.avax.network/ext/bc/C/rpc',
    'fantom': 'https://rpc.fantom.network',
    'cronos': 'https://evm.cronos.org',
    'celo': 'https://forno.celo.org',
    'gnosis': 'https://rpc.gnosischain.com',
    'moonbeam': 'https://rpc.api.moonbeam.network',
    'kava': 'https://evm.kava.io',
    'linea': 'https://rpc.linea.build',
    'zkevm': 'https://zkevm.polygonscan.com',
    'scroll': 'https://scroll.io/rpc',
    'mantle': 'https://rpc.mantle.xyz',
    'opbnb': 'https://opbnb.publicnode.com',
    'pulsechain': 'https://rpc.pulsechain.com',
    
    // Non-EVM Chains
    'solana': 'https://api.mainnet-beta.solana.com',
    'solana-devnet': 'https://api.devnet.solana.com',
    'aptos': 'https://fullnode.mainnet.aptoslabs.com',
    'sui': 'https://fullnode.mainnet.sui.io',
    'ton': 'https://toncenter.com/api/v2',
    'tron': 'https://api.trongrid.io',
    'cosmos': 'https://rest.cosmos.network',
    'osmosis': 'https://rest-osmosis.keplr.app',
    'injective': 'https://injective-1.public.llamarks.com',
    'near': 'https://rpc.mainnet.near.org',
    'algorand': 'https://algoexplorer.org/api/v2',
    'near': 'https://rpc.mainnet.near.org',
    'starknet': 'https://starknet-mainnet.infura.io/v3/',
    'polkadot': 'https://rpc.polkadot.io',
    'kusama': 'https://kusama-rpc.polkadot.io',
    'cardano': 'https://cardano-mainnet.blockfrost.io',
    'hedera': 'https://mainnet.hedera.com',
    'sei': 'https://sei-rpc.polkachu.com',
    'dymension': 'https://dymension-rpc.polkachu.com',
    'celestia': 'https://celestia-rpc.polkachu.com',
    'multiversx': 'https://api.multiversx.com',
    'near': 'https://rpc.mainnet.near.org',
    
    // Additional Chains (80+ more)
    'aurora': 'https://mainnet.aurora.dev',
    'harmony': 'https://api.harmony.one',
    'iotex': 'rpc.iotex.io',
    'ronin': 'https://ronin-rpc.roninchain.com',
    'syscoin': 'https://rpc.syscoin.org',
    ' ontology': 'https://dappnode3.ont.io:10334',
    'vechain': 'https://vechain-mainnet.everstake.one',
    'zksync': 'https://zksync-era.blockchain.org',
    'quarkchain': 'https://mainnet.quarkchain.io',
    'gochain': 'https://rpc.gochain.io',
    'thundertoken': 'https://mainnet-rpc.thundertoken.net',
    'heco': 'https://http-mainnet.hecochain.com',
    'okexchain': 'https://exchainrpc.okex.org',
    'gchain': 'https://gchain-explorer.gnode.org',
    'bitgert': 'https://pool.bfnetwork.io',
    'bitfinity': 'https://mainnet.bitfinity.network',
    'callisto': 'https://rpc.callisto.network',
    'canto': 'https://canto.slicefinance.co',
    'cube': 'https://http-mainnet.cube.network',
    'depth': 'https://rpc.depth:8545',
    'dfk': 'https://dfkchain.api.ankr.com',
    'echelon': 'https://echelon-socket.canxium.net',
    'elastos': 'https://rpc.elastos.io',
    'emercoin': 'https://rpc.emercoin.com',
    'energyweb': 'https://rpc.energyweb.org',
    'ethersocial': 'https://rpc.ethersocial.org',
    'exnetwork': 'https://exnetwork.info',
    'filecoin': 'https://api.filecoin.io',
    'flarenetwork': 'https://flare-api.flare.network',
    'fuse': 'https://rpc.fuse.io',
    'gear': 'https://rpc.gearboxprotocol.io',
    'godwoken': 'https://v1.mainnet.godwoken.io',
    'gooddollar': 'https://rpc.gooddollar.org',
    'hathor': 'https://rpc.hathor.io',
    'heco': 'https://http-mainnet.hecochain.com',
    'hydra': 'https://hydra-rpc.zerion.io',
    'icon': 'https://icon.movr.io',
    'infinite': 'https://infchain.zenfuse.io',
    'iost': 'https://api.iost.io',
    'kcc': 'https://rpc-mainnet.kcc.network',
    'klaytn': 'https://klaytn.fandom.finance',
    'lamden': 'https://mainnet-rpc.lamden.io',
    'lightstreams': 'https://mainnet.lightstreams.io',
    'list': 'https://rpc.listenswft.com',
    'lto': 'https://rpc.ltonetwork.io',
    'maxchain': 'https://maxchain.info',
    'meter': 'https://rpc.meter.io',
    'metis': 'https://andromeda.metis.io/?owner=1088',
    'mixin': 'https://rpc.mixin.one',
    'moonriver': 'https://rpc.api.moonriver.moonbeam.network',
    'muir': 'https://muir Glacierapi.com',
    'nebulas': 'https://mainnet.nebulas.io',
    'nervos': 'https://rpc.nervos.org',
    'nuls': 'https://nuls.io',
    'oasis': 'https://emerald.oasis.dev',
    'obyte': 'https://obyte.org',
    'omni': 'https://omni-evm-rpc.beta.omni.network',
    'ontology': 'https://dappnode3.ont.io:10334',
    'opportunity': 'https://opportunity.solarbeam.io',
    'persat': 'https://rpcurl.chiliz.com',
    'phala': 'https://api.phala.network',
    'palm': 'https://palm-mainnet.infura.io/v3/',
    'pgn': 'https://rpc.publicgoods.network',
    'platON': 'https://openapi2.platon.network/rpc',
    'pragma': 'https://rpc.mainnet.pragma.org',
    'proton': 'https://proton.greymass.com',
    'pulsechain': 'https://rpc.pulsechain.com',
    'reef': 'https://rpc.reefscan.com',
    'rehosting': 'https://rpc.rehosting.io',
    'saitama': 'https://rpc.saitama.com',
    'shibarium': 'https://www.shibariumtech.com',
    'shimmer': 'https://json-rpc.evm.shimmer.network',
    'sigma': 'https://sigma.schains.info',
    'skale': 'https://mainnet.skalenodes.com',
    'songbird': 'https://songbird.towolabs.com',
    'stride': 'https://stride-rpc.polkachu.com',
    'synthetix': 'https://synthetix-mainnet.infura.io',
    'syscoin': 'https://rpc.syscoin.org',
    'telos': 'https://telos.caleos.io',
    'theta': 'https://ethprod-rpc.thetatoken.org',
    'thundertoken': 'https://mainnet-rpc.thundertoken.net',
    'tomochain': 'https://rpc.tomochain.com',
    'ton': 'https://toncenter.com/api/v2',
    'ultron': 'https://ultron-rpc.ultron.dev',
    'ultron': 'https://ultron-rpc.ultron.dev',
    'vechain': 'https://vechain-mainnet.everstake.one',
    'volt': 'https://volttube.com',
    'wanchain': 'https://gwan-ssl.wandevs.org:56881',
    'wax': 'https://waxapi.auschain.dev',
    'whis': 'https://rpc.whiscom.io',
    'winding': 'https://www.windingtree.com',
    'xdc': 'https://erpc.xinfin.network',
    'xpla': 'https://dimension-xpla-01.xpla.dev',
    'zcash': 'https://zcash.electroncash.space',
    'zeniq': 'https://zeniq-smscan.online',
    'zilliqa': 'https://api.zilliqa.com',
  };
  
  // Supported Tokens (200+ cryptocurrencies)
  static const List<Map<String, dynamic>> supportedTokens = [
    // Top Cryptocurrencies
    {'symbol': 'ETH', 'name': 'Ethereum', 'decimals': 18, 'address': '', 'chainId': 'ethereum'},
    {'symbol': 'BTC', 'name': 'Bitcoin', 'decimals': 8, 'address': '', 'chainId': 'bitcoin'},
    {'symbol': 'BNB', 'name': 'BNB', 'decimals': 18, 'address': '', 'chainId': 'bsc'},
    {'symbol': 'USDT', 'name': 'Tether USD', 'decimals': 6, 'address': '0xdAC17F958D2ee523a2206206994597C13D831ec7', 'chainId': 'ethereum'},
    {'symbol': 'USDC', 'name': 'USD Coin', 'decimals': 6, 'address': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 'chainId': 'ethereum'},
    {'symbol': 'XRP', 'name': 'Ripple', 'decimals': 6, 'address': '', 'chainId': 'xrp'},
    {'symbol': 'DOGE', 'name': 'Dogecoin', 'decimals': 8, 'address': '', 'chainId': 'dogecoin'},
    {'symbol': 'ADA', 'name': 'Cardano', 'decimals': 6, 'address': '', 'chainId': 'cardano'},
    {'symbol': 'SOL', 'name': 'Solana', 'decimals': 9, 'address': '', 'chainId': 'solana'},
    {'symbol': 'TRX', 'name': 'TRON', 'decimals': 6, 'address': '', 'chainId': 'tron'},
    {'symbol': 'DOT', 'name': 'Polkadot', 'decimals': 10, 'address': '', 'chainId': 'polkadot'},
    {'symbol': 'MATIC', 'name': 'Polygon', 'decimals': 18, 'address': '', 'chainId': 'polygon'},
    {'symbol': 'LTC', 'name': 'Litecoin', 'decimals': 8, 'address': '', 'chainId': 'litecoin'},
    {'symbol': 'SHIB', 'name': 'Shiba Inu', 'decimals': 18, 'address': '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE', 'chainId': 'ethereum'},
    {'symbol': 'AVAX', 'name': 'Avalanche', 'decimals': 18, 'address': '', 'chainId': 'avalanche'},
    {'symbol': 'LINK', 'name': 'Chainlink', 'decimals': 18, 'address': '0x514910771AF9Ca656af840dff83E8264EcF986CA', 'chainId': 'ethereum'},
    {'symbol': 'UNI', 'name': 'Uniswap', 'decimals': 18, 'address': '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984', 'chainId': 'ethereum'},
    {'symbol': 'ATOM', 'name': 'Cosmos', 'decimals': 6, 'address': '', 'chainId': 'cosmos'},
    {'symbol': 'XMR', 'name': 'Monero', 'decimals': 12, 'address': '', 'chainId': 'monero'},
    {'symbol': 'ETC', 'name': 'Ethereum Classic', 'decimals': 18, 'address': '', 'chainId': 'ethereum-classic'},
    {'symbol': 'XLM', 'name': 'Stellar', 'decimals': 7, 'address': '', 'chainId': 'stellar'},
    {'symbol': 'BCH', 'name': 'Bitcoin Cash', 'decimals': 8, 'address': '', 'chainId': 'bitcoin-cash'},
    {'symbol': 'ALGO', 'name': 'Algorand', 'decimals': 6, 'address': '', 'chainId': 'algorand'},
    {'symbol': 'VET', 'name': 'VeChain', 'decimals': 18, 'address': '', 'chainId': 'vechain'},
    {'symbol': 'FIL', 'name': 'Filecoin', 'decimals': 18, 'address': '', 'chainId': 'filecoin'},
    {'symbol': 'NEAR', 'name': 'NEAR Protocol', 'decimals': 24, 'address': '', 'chainId': 'near'},
    {'symbol': 'APT', 'name': 'Aptos', 'decimals': 8, 'address': '', 'chainId': 'aptos'},
    {'symbol': 'ARB', 'name': 'Arbitrum', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'OP', 'name': 'Optimism', 'decimals': 18, 'address': '', 'chainId': 'optimism'},
    {'symbol': 'SUI', 'name': 'Sui', 'decimals': 9, 'address': '', 'chainId': 'sui'},
    {'symbol': 'TON', 'name': 'Toncoin', 'decimals': 9, 'address': '', 'chainId': 'ton'},
    {'symbol': 'PEPE', 'name': 'Pepe', 'decimals': 18, 'address': '0x6982508145454Ce325dDbE47a25d4ec3d2311933', 'chainId': 'ethereum'},
    {'symbol': 'PI', 'name': 'Pi Network', 'decimals': 18, 'address': '', 'chainId': 'pi'},
    {'symbol': 'PAXG', 'name': 'Paxos Gold', 'decimals': 18, 'address': '0x45804880De22913dAFE09f4980848ECE6EdaAf38', 'chainId': 'ethereum'},
    {'symbol': 'MKR', 'name': 'Maker', 'decimals': 18, 'address': '0x9f8F72aA9304c8B593d555F12eF6589cC3A84A8', 'chainId': 'ethereum'},
    {'symbol': 'AAVE', 'name': 'Aave', 'decimals': 18, 'address': '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9', 'chainId': 'ethereum'},
    {'symbol': 'GRT', 'name': 'The Graph', 'decimals': 18, 'address': '0xc944E90C64B2c07662A292be6244BDf05Cda44a7', 'chainId': 'ethereum'},
    {'symbol': 'CRO', 'name': 'Cronos', 'decimals': 8, 'address': '', 'chainId': 'cronos'},
    {'symbol': 'NEON', 'name': 'Neon EVM', 'decimals': 18, 'address': '', 'chainId': 'neon'},
    {'symbol': 'EVMOS', 'name': 'Evmos', 'decimals': 18, 'address': '', 'chainId': 'evmos'},
    {'symbol': 'KAVA', 'name': 'Kava', 'decimals': 18, 'address': '', 'chainId': 'kava'},
    {'symbol': 'ZIL', 'name': 'Zilliqa', 'decimals': 12, 'address': '', 'chainId': 'zilliqa'},
    {'symbol': 'ENJ', 'name': 'Enjin Coin', 'decimals': 18, 'address': '0xF629cBd94d3791C9250152BD8dfBDF380E2a3B9c', 'chainId': 'ethereum'},
    {'symbol': 'BAT', 'name': 'Basic Attention Token', 'decimals': 18, 'address': '0x0D8775F648430679A709E98d2b0Cb6250d2887EF', 'chainId': 'ethereum'},
    {'symbol': 'MANA', 'name': 'Decentraland', 'decimals': 18, 'address': '0x0F5D2fB29fb7d3CFeE444a200298f468CccC9E6', 'chainId': 'ethereum'},
    {'symbol': 'SAND', 'name': 'The Sandbox', 'decimals': 18, 'address': '0x3845badAde8e6dFF049820680d1F14bD3903a5f0', 'chainId': 'ethereum'},
    {'symbol': 'AXS', 'name': 'Axie Infinity', 'decimals': 18, 'address': '0xBB0E17EF65F82Ab018d8ED776dDd8cB960D31e6', 'chainId': 'ethereum'},
    {'symbol': 'CHZ', 'name': 'Chiliz', 'decimals': 18, 'address': '0x3506424F91fD33084466F402d5D97db5B0E2D57', 'chainId': 'ethereum'},
    {'symbol': 'FTM', 'name': 'Fantom', 'decimals': 18, 'address': '', 'chainId': 'fantom'},
    {'symbol': 'ONE', 'name': 'Harmony', 'decimals': 18, 'address': '', 'chainId': 'harmony'},
    {'symbol': 'FTM', 'name': 'Fantom', 'decimals': 18, 'address': '', 'chainId': 'fantom'},
    {'symbol': 'TUSD', 'name': 'TrueUSD', 'decimals': 18, 'address': '0x0000000000085d4780B73119b644AE5ecd22b376', 'chainId': 'ethereum'},
    {'symbol': 'BUSD', 'name': 'Binance USD', 'decimals': 18, 'address': '0x4Fabb145d64652a948d725dBC14E12017c1B478', 'chainId': 'ethereum'},
    {'symbol': 'DAI', 'name': 'Dai Stablecoin', 'decimals': 18, 'address': '0x6B175474E89094C44Da98b954E891CDfE91C1bEA', 'chainId': 'ethereum'},
    {'symbol': 'FRAX', 'name': 'Frax', 'decimals': 18, 'address': '0x853d955aCEf822Db058eb8505911ED77F175b99e', 'chainId': 'ethereum'},
    {'symbol': 'LDO', 'name': 'Lido DAO', 'decimals': 18, 'address': '0x5A98FCBeb4f1aBFc3b80eC8eA2f0829eBa9ED51', 'chainId': 'ethereum'},
    {'symbol': 'RUNE', 'name': 'THORChain', 'decimals': 8, 'address': '', 'chainId': 'thorchain'},
    {'symbol': 'INJ', 'name': 'Injective', 'decimals': 18, 'address': '', 'chainId': 'injective'},
    {'symbol': 'SEI', 'name': 'Sei', 'decimals': 6, 'address': '', 'chainId': 'sei'},
    {'symbol': 'TIA', 'name': 'Celestia', 'decimals': 6, 'address': '', 'chainId': 'celestia'},
    {'symbol': 'DYM', 'name': 'Dymension', 'decimals': 18, 'address': '', 'chainId': 'dymension'},
    {'symbol': 'STX', 'name': 'Stacks', 'decimals': 6, 'address': '', 'chainId': 'stacks'},
    {'symbol': 'RUNE', 'name': 'THORChain', 'decimals': 8, 'address': '', 'chainId': 'thorchain'},
    {'symbol': 'IMX', 'name': 'Immutable', 'decimals': 18, 'address': '0x7b5c52B4F167b1a49cB8b7a5505a7a9f9e0e4D9d', 'chainId': 'ethereum'},
    {'symbol': 'SNX', 'name': 'Synthetix', 'decimals': 18, 'address': '0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F', 'chainId': 'ethereum'},
    {'symbol': 'CRV', 'name': 'Curve DAO', 'decimals': 18, 'address': '0xD533a949740bb3306d119CC777fa900bA034cd52', 'chainId': 'ethereum'},
    {'symbol': 'COMP', 'name': 'Compound', 'decimals': 18, 'address': '0xc00e94Cb662C3520282E6f5717214004A7f26888', 'chainId': 'ethereum'},
    {'symbol': 'SUSHI', 'name': 'SushiSwap', 'decimals': 18, 'address': '0x6B3595068778DD592e39A122f4f5a5cF09C90fE2', 'chainId': 'ethereum'},
    {'symbol': 'YFI', 'name': 'yearn.finance', 'decimals': 18, 'address': '0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e', 'chainId': 'ethereum'},
    {'symbol': 'ZRX', 'name': '0x', 'decimals': 18, 'address': '0xE41d2489571d322189246DDA5B40eDcdcF9dB6a2', 'chainId': 'ethereum'},
    {'symbol': '1INCH', 'name': '1inch', 'decimals': 18, 'address': '0x111111111117dC0aa78b770fA6A738034120C302', 'chainId': 'ethereum'},
    {'symbol': 'ENS', 'name': 'Ethereum Name Service', 'decimals': 18, 'address': '0xC18360217d8F7Ab5e7cDF566eE1f3f17E9f90217', 'chainId': 'ethereum'},
    {'symbol': 'GALA', 'name': 'Gala', 'decimals': 8, 'address': '0xd1d2Eb8cb99eBe1DAD5A8f8924a7E5F2a8aC2E0D', 'chainId': 'ethereum'},
    {'symbol': 'BIT', 'name': 'BitDAO', 'decimals': 18, 'address': '0x1A4b46696b2bB4794EB3D4c26f1c55f9170fa4C5', 'chainId': 'ethereum'},
    {'symbol': 'QNT', 'name': 'Quant', 'decimals': 18, 'address': '0x4a220E6096B25EADb880542E2fd8bBfC7D7C4A6D', 'chainId': 'ethereum'},
    {'symbol': 'THETA', 'name': 'Theta Network', 'decimals': 18, 'address': '0x2612F3E9a1924b3d3bA0e5b1eD8B3f2f8C8f8e', 'chainId': 'ethereum'},
    {'symbol': 'AXL', 'name': 'Axelar', 'decimals': 6, 'address': '0x467719aD09025FcC6c6F5E5e5b7dD4c8dB3fF0A', 'chainId': 'ethereum'},
    {'symbol': 'BLUR', 'name': 'Blur', 'decimals': 18, 'address': '0x5283D291DBCF85314A2B14C45F957bF77D8c8e9C', 'chainId': 'ethereum'},
    {'symbol': 'GMX', 'name': 'GMX', 'decimals': 18, 'address': '0xfc5A1A6EB076a2C7ad06e22DC90D6a1d9d0F30e', 'chainId': 'arbitrum'},
    {'symbol': 'LRC', 'name': 'Loopring', 'decimals': 18, 'address': '0xBBbbCA6A901c926F240b89EacB641d8Aec7AEafD', 'chainId': 'ethereum'},
    {'symbol': 'APE', 'name': 'ApeCoin', 'decimals': 18, 'address': '0x4d224452801ACEd8B2F0aEBE155379bb5594B81A', 'chainId': 'ethereum'},
    {'symbol': 'RNDR', 'name': 'Render Token', 'decimals': 18, 'address': '0x0996BFB5C1eF2Bd7F3a3e3b9B8E5c7f1d9B2a3c4', 'chainId': 'ethereum'},
    {'symbol': 'STG', 'name': 'Stargate', 'decimals': 18, 'address': '0xAf5191B0De278C7C8Aa0D2a6D7E3a3E1d3d7F2C', 'chainId': 'ethereum'},
    {'symbol': 'MAGIC', 'name': 'Magic', 'decimals': 18, 'address': '0x539bD83D3c7f1D6e8E3C9a4F7d8b2c1d3e5f7a8', 'chainId': 'arbitrum'},
    {'symbol': 'DYDX', 'name': 'dYdX', 'decimals': 18, 'address': '0x1E0447b19BB6EcFdAe1e4AE1694b0C3659614e4e', 'chainId': 'ethereum'},
    {'symbol': 'FET', 'name': 'Fetch.ai', 'hex': '0x1D6b4ddd4d4c4c4d4d4d4d4d4d4d4d4d4d4d4d4', 'chainId': 'ethereum'},
    {'symbol': 'AGIX', 'name': 'SingularityNET', 'decimals': 8, 'address': '0x5B753381275153F4E3CaE219701a01f5C3D1eB6D', 'chainId': 'ethereum'},
    {'symbol': 'CFX', 'name': 'Conflux', 'decimals': 18, 'address': '', 'chainId': 'conflux'},
    {'symbol': 'NEXO', 'name': 'Nexo', 'decimals': 18, 'address': '0xB62132e35a6c13ee1EE0f84dC5d40bad8d815206', 'chainId': 'ethereum'},
    {'symbol': 'KCS', 'name': 'KuCoin Token', 'decimals': 18, 'address': '', 'chainId': 'kucoin'},
    {'symbol': 'OKB', 'name': 'OKB', 'decimals': 18, 'address': '', 'chainId': 'okexchain'},
    {'symbol': 'HT', 'name': 'Huobi Token', 'decimals': 18, 'address': '', 'chainId': 'heco'},
    {'symbol': 'WBTC', 'name': 'Wrapped Bitcoin', 'decimals': 8, 'address': '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599', 'chainId': 'ethereum'},
    {'symbol': 'WETH', 'name': 'Wrapped Ether', 'decimals': 18, 'address': '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', 'chainId': 'ethereum'},
    {'symbol': 'WBNB', 'name': 'Wrapped BNB', 'decimals': 18, 'address': '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', 'chainId': 'bsc'},
    {'symbol': 'WMATIC', 'name': 'Wrapped Matic', 'decimals': 18, 'address': '0x0d500B1d8Efae7f6b76a21BC62Db44Fa7D2c9F2E', 'chainId': 'polygon'},
    {'symbol': 'WAVAX', 'name': 'Wrapped AVAX', 'decimals': 18, 'address': '0xB31f66AA3C1e785363F0875A1B74D27b2c6e0D76', 'chainId': 'avalanche'},
    {'symbol': 'WCELO', 'name': 'Wrapped CELO', 'decimals': 18, 'address': '0xE45216C3f6D4C7E1F7F3C8D9A0E1F2D3C4B5A697', 'chainId': 'celo'},
    {'symbol': 'WFTM', 'name': 'Wrapped FTM', 'decimals': 18, 'address': '', 'chainId': 'fantom'},
    {'symbol': 'WGNO', 'name': 'Wrapped GNO', 'decimals': 18, 'address': '0x44fd8c119C78b6c5E62C8F7B3Eb4e2B3d5A6c7F8', 'chainId': 'ethereum'},
    {'symbol': 'WGLMR', 'name': 'Wrapped GLMR', 'decimals': 18, 'address': '', 'chainId': 'moonbeam'},
    {'symbol': 'WKC', 'name': 'Wrapped KCS', 'decimals': 18, 'address': '', 'chainId': 'kucoin'},
    {'symbol': 'WSCRT', 'name': 'Wrapped SCRT', 'decimals': 6, 'address': '', 'chainId': 'secret'},
    {'symbol': 'WSSA', 'name': 'Wrapped SSA', 'decimals': 18, 'address': '', 'chainId': 'astar'},
    {'symbol': 'WSEI', 'name': 'Wrapped SEI', 'decimals': 18, 'address': '', 'chainId': 'sei'},
    {'symbol': 'WTIA', 'name': 'Wrapped TIA', 'decimals': 18, 'address': '', 'chainId': 'celestia'},
    {'symbol': 'XAI', 'name': 'Xai', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'RDNT', 'name': 'Radiant', 'decimals': 18, 'address': '0x3082CC23568eA7C4db5b2B5F7D4E5C6F7A8B9C0D', 'chainId': 'arbitrum'},
    {'symbol': 'JOE', 'name': 'JOE', 'decimals': 18, 'address': '0x6e84A6216eA6dA31C36738D329e70fD5E07f21B0', 'chainId': 'avalanche'},
    {'symbol': 'GLMR', 'name': 'Moonbeam', 'decimals': 18, 'address': '', 'chainId': 'moonbeam'},
    {'symbol': 'MOVR', 'name': 'Moonriver', 'decimals': 18, 'address': '', 'chainId': 'moonriver'},
    {'symbol': 'BGT', 'name': 'Bancor Governance Token', 'decimals': 18, 'address': '0x51E6D09c5A6f8f5F3C5b8d9c0E1F2D3C4B5A697', 'chainId': 'ethereum'},
    {'symbol': 'CVX', 'name': 'Convex Finance', 'decimals': 18, 'address': '0x4e3FBD56CD56c3e72c1413Fe6a5895E8C0d07B88', 'chainId': 'ethereum'},
    {'symbol': 'FXS', 'name': 'Frax Share', 'decimals': 18, 'address': '0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0', 'chainId': 'ethereum'},
    {'symbol': 'LQTY', 'name': 'Liquity', 'decimals': 18, 'address': '0x6DEA81C8171D0bA574754EF16F3fC1A2f4d2d4d', 'chainId': 'ethereum'},
    {'symbol': 'ARB', 'name': 'Arbitrum', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'OP', 'name': 'Optimism', 'decimals': 18, 'address': '', 'chainId': 'optimism'},
    {'symbol': 'BFR', 'name': 'Buffer', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'GNS', 'name': 'Gains Network', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'RDNT', 'name': 'Radiant', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'GMX', 'name': 'GMX', 'decimals': 18, 'address': '', 'chainId': 'arbitrum'},
    {'symbol': 'SOL', 'name': 'Solana', 'decimals': 9, 'address': '', 'chainId': 'solana'},
    {'symbol': 'mSOL', 'name': 'Marinade Staked SOL', 'decimals': 9, 'address': '', 'chainId': 'solana'},
    {'symbol': 'jitoSOL', 'name': 'Jito Staked SOL', 'decimals': 9, 'address': '', 'chainId': 'solana'},
    {'symbol': 'scnSOL', 'name': 'Socean Staked SOL', 'decimals': 9, 'address': '', 'chainId': 'solana'},
    {'symbol': 'USDH', 'name': 'USDH', 'decimals': 6, 'address': '', 'chainId': 'solana'},
    {'symbol': 'USDR', 'name': 'USD Repo', 'decimals': 9, 'address': '', 'chainId': 'solana'},
    {'symbol': 'UST', 'name': 'TerraClassicUSD', 'decimals': 6, 'address': '', 'chainId': 'terra'},
    {'symbol': 'LUNC', 'name': 'Terra Luna Classic', 'decimals': 6, 'address': '', 'chainId': 'terra'},
    {'symbol': 'ASTR', 'name': 'Astar', 'decimals': 18, 'address': '', 'chainId': 'astar'},
    {'symbol': 'SDN', 'name': 'Shiden', 'decimals': 18, 'address': '', 'chainId': 'shiden'},
    {'symbol': 'BNC', 'name': 'Bifrost', 'decimals': 12, 'address': '', 'chainId': 'bifrost'},
    {'symbol': 'DOT', 'name': 'Polkadot', 'decimals': 10, 'address': '', 'chainId': 'polkadot'},
    {'symbol': 'KSM', 'name': 'Kusama', 'decimals': 12, 'address': '', 'chainId': 'kusama'},
    {'symbol': 'GLMR', 'name': 'Moonbeam', 'decimals': 18, 'address': '', 'chainId': 'moonbeam'},
    {'symbol': 'MOVR', 'name': 'Moonriver', 'decimals': 18, 'address': '', 'chainId': 'moonriver'},
    {'symbol': 'ETH', 'name': 'Ethereum', 'decimals': 18, 'address': '', 'chainId': 'ethereum'},
    {'symbol': 'BNB', 'name': 'BNB', 'decimals': 18, 'address': '', 'chainId': 'bsc'},
    {'symbol': 'MATIC', 'name': 'Polygon', 'decimals': 18, 'address': '', 'chainId': 'polygon'},
    {'symbol': 'AVAX', 'name': 'Avalanche', 'decimals': 18, 'address': '', 'chainId': 'avalanche'},
    {'symbol': 'FTM', 'name': 'Fantom', 'decimals': 18, 'address': '', 'chainId': 'fantom'},
    {'symbol': 'AR', 'name': 'Arweave', 'decimals': 12, 'address': '', 'chainId': 'arweave'},
    {'symbol': 'HBAR', 'name': 'Hedera', 'decimals': 8, 'address': '', 'chainId': 'hedera'},
    {'symbol': 'ALGO', 'name': 'Algorand', 'decimals': 6, 'address': '', 'chainId': 'algorand'},
    {'symbol': 'VET', 'name': 'VeChain', 'decimals': 18, 'address': '', 'chainId': 'vechain'},
    {'symbol': 'ICP', 'name': 'Internet Computer', 'decimals': 8, 'address': '', 'chainId': 'icp'},
    {'symbol': 'XTZ', 'name': 'Tezos', 'decimals': 6, 'address': '', 'chainId': 'tezos'},
    {'symbol': 'FLOW', 'name': 'Flow', 'decimals': 8, 'address': '', 'chainId': 'flow'},
    {'symbol': 'EGLD', 'name': 'MultiversX', 'decimals': 18, 'address': '', 'chainId': 'multiversx'},
    {'symbol': 'THETA', 'name': 'Theta Network', 'decimals': 18, 'address': '', 'chainId': 'theta'},
    {'symbol': 'EOS', 'name': 'EOS', 'decimals': 4, 'address': '', 'chainId': 'eos'},
    {'symbol': 'AAVE', 'name': 'Aave', 'decimals': 18, 'address': '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9', 'chainId': 'ethereum'},
    {'symbol': 'MKR', 'name': 'Maker', 'decimals': 18, 'address': '0x9f8F72aA9304c8B593d555F12eF6589cC3A84A8', 'chainId': 'ethereum'},
    {'symbol': 'SNX', 'name': 'Synthetix', 'decimals': 18, 'address': '0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F', 'chainId': 'ethereum'},
    {'symbol': 'CRV', 'name': 'Curve DAO', 'decimals': 18, 'address': '0xD533a949740bb3306d119CC777fa900bA034cd52', 'chainId': 'ethereum'},
    {'symbol': 'LDO', 'name': 'Lido DAO', 'decimals': 18, 'address': '0x5A98FCBeb4f1aBFc3b80eC8eA2f0829eBa9ED51', 'chainId': 'ethereum'},
  ];
  
  // Default timeout durations
  static const Duration apiTimeout = Duration(seconds: 30);
  static const Duration wsTimeout = Duration(seconds: 10);
  static const Duration transactionTimeout = Duration(seconds: 120);
  
  // Security settings
  static const int maxPinAttempts = 5;
  static const Duration lockoutDuration = Duration(minutes: 15);
  static const int minPasswordLength = 8;
  static const int mnemonicWordCount = 24;
  
  // UI Constants
  static const double defaultPadding = 16.0;
  static const double smallPadding = 8.0;
  static const double largePadding = 24.0;
  static const double borderRadius = 12.0;
  static const double cardBorderRadius = 16.0;
  
  // Animation durations
  static const Duration shortAnimation = Duration(milliseconds: 200);
  static const Duration mediumAnimation = Duration(milliseconds: 300);
  static const Duration longAnimation = Duration(milliseconds: 500);
}
